### ISSUE TITLE
development  dimension of full_triangle is not as expected 

### ISSUE THREAD

**Issue by Barmus** [casact/chainladder-python#104]
The origin dev_triangle got 9 columns of development year , But after applyed the Baisc Chainladder method to “squares” the Triangle, full_triangle had 11 columns of  development year. How do I control the output? Thank you !

![image](https://user-images.githubusercontent.com/8174987/101617629-d1b21800-3a4b-11eb-8f2a-2cf39ef36f7f.png)

**Comment by jbogaardt** [comment]
Thanks for the question @Barmus .  Any of the IBNR method will yield a development dimension with ages of the original triangle plus ages one year out (for run-off analysis) plus an age at ultimate.  You can always slice the development periods you want.

For example:
```python 
full_triangle_[~full_triangle_.development.isin([108,120])] # Eliminates ages 108 and 120
full_triangle.iloc[..., :9] # Eliminates ages 120 and 9999, but would eliminate tail if you had one.
```
