### ISSUE TITLE
Too small LDFs included in exponential tail curve fit

### ISSUE THREAD

**Issue by Brian-13** [casact/chainladder-python#113]
When fitting an exponential tail curve with the log regression, only LDFs < 1.0 are excluded. However, also LDFs close to 1, e.g. <1.0001 can distort the tail fit considerably.

**Suggestion:**
Replace in curve.py rows 111-113
`if self.errors == "ignore":`
`_w[_y <= 1.0] = 0`
`_y[_y <= 1.0] = 1.01`

with something like

`if self.errors == "ignore":`
`_w[_y <= threshold] = 0`
`_y[_y <= threshold] = 1.01`

and let the user define the `threshold` with a default like 1.0001 or 1.00001.

**Comment by jbogaardt** [comment]
This us a good suggestion and probably not too difficult to do.

**Comment by jbogaardt** [comment]
@Brian-13 , you seem to be willing to dive into the modules and you've forked the code. Would you like me to assign this to you?

**Comment by jbogaardt** [comment]
Another alternative is to allow for more refined controls than is currently supported by the `fit_period` parameter.

**Comment by Brian-13** [comment]
Hi @jbogaardt, yes, feel free to assign it to me. I'm currently testing a solution and make this available in the next days.

**Comment by jbogaardt** [comment]
closed by #114
