### ISSUE TITLE
VotingChainladder enhancements

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#117]
Would like to get additional model properties functioning with the `VotingChainladder` estimator prior to release.

```python
import chainladder as cl
raa = cl.load_sample('RAA')

bcl1 = cl.Pipeline(steps=[('dev', cl.Development(average='volume')), ('model', cl.Chainladder())])
bcl2 = cl.Pipeline(steps=[('dev', cl.Development(average='simple')), ('model', cl.Chainladder())])

estimators = [('bcl1', bcl1), ('bcl2', bcl2)]
vot = cl.VotingChainladder(estimators=estimators)
vot.fit(raa)

assert abs((bcl1.fit(raa).named_steps['model'].full_expectation_ + bcl2.fit(raa).named_steps['model'].full_expectation_)/2 - vot.full_expectation_).max().max()< 1e-4
```

**Comment by jbogaardt** [comment]
This will be much harder to do with stochastic properties and perhaps should be limited to deterministic approaches.  Ideally, we could determine the implied `ldf_` so that `full_expectation_` and `full_triangle_` produce blended results.

**Comment by jbogaardt** [comment]
Another thing I think would be really cool enhancement would be to allow the weight to optionally/additionally take on the form of a `dict` or `callable`.  This might help the use cases where a general form can be described:
```python
# Initial setup
import chainladder as cl
raa = cl.load_sample('raa')
bcl1 = cl.Pipeline(steps=[('dev', cl.Development(average='volume')), ('model', cl.Chainladder())])
bcl2 = cl.Pipeline(steps=[('dev', cl.Development(average='simple')), ('model', cl.Chainladder())])
estimators = [('bcl1', bcl1), ('bcl2', bcl2)]
```
### Dict approach
Any origin period not mentioned in dict gets default averaging behavior
```python
dict_weight = {'1990':(1,0), '1989':(.8, .2)} 
vot = cl.VotingChainladder(estimators=estimators, weight=dict_weight)
```
### Callable approach
For callable weight, anything that can map onto the origin vector should be permissible
```python
callable_weight = lambda origin : (1, 0) if origin.year > 1985 else (.5,.5)

# If it works for origin mapping...
raa.origin.map(callable_weight) # This works
# then it should work in the VotingChainladder estmator
vot = cl.VotingChainladder(estimators=estimators, weight=callable_weight) 
```
@cbalona and others, thoughts/concerns?

**Comment by jbogaardt** [comment]
There also appears to be some unaccounted for mutation/side-effect we should resolve. Notice the second "refit" of the estimator.
```python
import chainladder as cl

raa = cl.load_sample('RAA')
cl_ult = cl.Chainladder().fit(raa).ultimate_ # Chainladder Ultimate
apriori = cl_ult * 0 + (float(cl_ult.sum()) / 10) # Mean Chainladder Ultimate

bcl = cl.Chainladder()
bf = cl.BornhuetterFerguson()
cc = cl.CapeCod()

estimators = [('bcl', bcl), ('bf', bf), ('cc', cc)]

vot = cl.VotingChainladder(estimators=estimators)
vot.fit(raa, sample_weight=apriori) # Works
vot.fit(raa, sample_weight=apriori) # Fails
```

**Comment by jbogaardt** [comment]
I've split apart "workflow" into "adjustments" and "workflow" and moved the ensemble voter into "workflow".

**Comment by cbalona** [comment]
> ```python
> import chainladder as cl
> raa = cl.load_sample('RAA')
> 
> bcl1 = cl.Pipeline(steps=[('dev', cl.Development(average='volume')), ('model', cl.Chainladder())])
> bcl2 = cl.Pipeline(steps=[('dev', cl.Development(average='simple')), ('model', cl.Chainladder())])
> 
> estimators = [('bcl1', bcl1), ('bcl2', bcl2)]
> vot = cl.VotingChainladder(estimators=estimators)
> vot.fit(raa)
> 
> assert abs((bcl1.fit(raa).named_steps['model'].full_expectation_ + bcl2.fit(raa).named_steps['model'].full_expectation_)/2 - vot.full_expectation_).max().max()< 1e-4
> ```

I agree with getting this working on deterministic first. One could apply the weights to the `full_expectation_` to get a "voted" `full_expectation_`, and then get the implied LDFs like that?

**Comment by cbalona** [comment]
> Another thing I think would be really cool enhancement would be to allow the weight to optionally/additionally take on the form of a dict or callable. This might help the use cases where a general form can be described:

I really like these enhancements, much more powerful and user friendly.

These necessitate a more sophisticated validation of the weights that incorporates the origin index:
1. If plain array is provided, check the dimension match (as it does currently)
2. if origins provided (e.g. through dict) check that all origin periods are allocated and apply the default for unallocated (in future perhaps provide choice of functionality for omitted origins, e.g. applying first estimator). Provide an exception on origins that don't exist.
3. The callable is less complex than 2. We could just convert the weights as follows:
`weights = np.array([*X.origin.map(callable_weight)])`

There may be value in converting the weights into a `Triangle` themselves to ease some of the above and align origin periods?

@jbogaardt I am happy to take a stab at it over the next week or two.

**Comment by cbalona** [comment]
> ```python
> import chainladder as cl
> 
> raa = cl.load_sample('RAA')
> cl_ult = cl.Chainladder().fit(raa).ultimate_ # Chainladder Ultimate
> apriori = cl_ult * 0 + (float(cl_ult.sum()) / 10) # Mean Chainladder Ultimate
> 
> bcl = cl.Chainladder()
> bf = cl.BornhuetterFerguson()
> cc = cl.CapeCod()
> 
> estimators = [('bcl', bcl), ('bf', bf), ('cc', cc)]
> 
> vot = cl.VotingChainladder(estimators=estimators)
> vot.fit(raa, sample_weight=apriori) # Works
> vot.fit(raa, sample_weight=apriori) # Fails
> ```

This is due to adding a new axis so that the weights can multiply with the ultimates. When refitting, it is adding a 6th axis. Should be a quick easy fix. It may also be avoided through better handling of the weights as per my previous comment.

**Comment by jbogaardt** [comment]
I also must say, in general and after reviewing your code,  you take scikit-learn integration to a whole new level.  I've mostly approached this with basic compliance of end-user experience in mind.  Undoubtedly I am leaving things on the table, like `n_jobs` support and logging apparent in yours.  I think you have a clearer picture of Estimator anatomy than I do.  In the future, please don't hesitate to suggest improvements that all estimators can benefit from.

**Comment by jbogaardt** [comment]
> 2\. if origins provided (e.g. through dict) check that all origin periods are allocated and apply the default for unallocated (in future perhaps provide choice of functionality for omitted origins, e.g. applying first estimator). Provide an exception on origins that don't exist.

This may help reduce the complexity of the dictionary approach:
```python
import chainladder as cl
raa = cl.load_sample('raa')

dict_weight = {'1989':(1, 0), '1988': (0.75, 0.25)}

# Convert dict_weight into a mapping dictionary
mapping_dict = {raa.origin[raa.origin==k][0] :v for k, v in dict_weight.items()}
# Fill in missing values
missing = {k: (0.5, 0.5) for k in raa.origin[~raa.origin.isin(mapping_dict.keys())]}

# Use it in same way as the callable method
raa.origin.map({**mapping_dict, **missing})
```

**Comment by cbalona** [comment]
> I also must say, in general and after reviewing your code, you take scikit-learn integration to a whole new level. I've mostly approached this with basic compliance of end-user experience in mind. Undoubtedly I am leaving things on the table, like `n_jobs` support and logging apparent in yours. I think you have a clearer picture of Estimator anatomy than I do. In the future, please don't hesitate to suggest improvements that all estimators can benefit from.

Thank you. I have come across a one or two areas where I think deeper integration can be made, but haven't actually thought deeply about it. I will be sure to open up some issues as I come across them again and suggest some improvements.
