### ISSUE TITLE
AttributeError in Triangle when run with NumPy 1.20.01

### ISSUE THREAD

**Issue by holmen1** [casact/chainladder-python#121]
I make a dataframe from csv as described in
/master/docs/tutorials/triangle-tutorial.ipynb,
which I then use as data in Triangle().

That runs well in a Jupyter notebook.

Moving that code to a .py-file in PyCharm i get:

  **File "/venv/lib/python3.8/site-packages/chainladder/core/base.py", line 46, in __init__
    check = [check] if check.__class__.__name__ == "dtype" else check.to_list()
AttributeError: 'numpy.dtype[int64]' object has no attribute 'to_list'**

Changing that line from
`        check = [check] if check.__class__.__name__ == "dtype" else check.to_list()`
to
`        check = [check] if check.__class__.__name__ == "dtype[int64]" else check.to_list()`
resoved the error.

**Comment by holmen1** [comment]
Python versions:
in Notebook = 3.7.7
in PyCharm = 3.8.2

**Comment by jbogaardt** [comment]
Thank you for reporting AND suggesting a fix! This is a strange error. What are the pandas versions?

My struggle is that  "dtype[int64]" is not a valid class name in python, so `__class__.__name__=="dtype[int64]"` should fail.
The purpose of this check is to ensure any dataframe columns passed to the `Triangle.columns` argument are numeric.  But there are a lot of numeric column types ('int', 'int32', 'int64', 'float', 'float32', 'float64', ...).  So I'm not comfortable referencing "int64" without understanding it better.

`check = [check] if check.__class__.__name__ == "dtype" else check.to_list()` is there to handle different outputs from calling dtype on a single column (`pd.Series.dtypes`) which returns a single dtype vs multiple columns (`pd.DataFrame.dtypes`) which returns a Series of dtypes.  Both are converted to a list.  The list is then checked for whether "object"  is in it which typically represents non-numeric types and throws an error if you're trying to make a Triangle out of, say str data.  Arguably, this misses non-numeric types that are not "object" dtypes such as dates, but that doesn't sound like your issue.

**Comment by holmen1** [comment]
NumPy is the culprit! it's version 1.20.01 that causes the error.

Setup below runs.

INSTALLED VERSIONS
------------------
python           : 3.8.2.final.0
pandas           : 1.2.2
numpy            : 1.18.4

**Comment by jbogaardt** [comment]
Nice work narrowing it down.  We can generalize the code to support numpy==1.2.1 and prior.
