### ISSUE TITLE
CapeCod should inherit from Benktander

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#124]
`CapeCod` is really just a `Benktander` method with a mechanism for deriving the `apriori`.  `Benkatnder` supports `n_iters` for iterated calcs as well as `apriori_sigma` for use in with the `BootstrapODPSample` estimator. It would be nice to extend the `CapeCod` functionality to include these as well.

**Comment by RonRichman** [comment]
John, is it Benktander or, more simply, just a simple BF with a mechanism for apriori?

**Comment by jbogaardt** [comment]
It's true I have not seen any literature on an "iterated" `CapeCod`, and have only seen the simple case of the BF which itself is a special case of `Benktander.n_iters=1`.  But why not allow for the full [iterated formula](https://chainladder-python.readthedocs.io/en/latest/modules/methods.html#iterations) in the `CapeCod` with the default of the BF case?  I suppose if an "iterated" `CapeCod` is a separate/distinct estimator, then it makes sense to force the existing `CapeCod` to `n_iters=1` as is done with the `BornhuetterFerguson` estimator.  IDK, I'm open to either.

Either way, I will probably inherit from Benktander anyway and force `n_iters` to 1 or not.

**Comment by RonRichman** [comment]
This comment inspired me to think a bit more about how one can derive the GCC from the Benktander method. I might blog about it, if that's ok @jbogaardt?

**Comment by jbogaardt** [comment]
Of course! I look forward to reading it.
