### ISSUE TITLE
BarnettZenwirth

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#131]
With the `DevelopmentML` framework, we can recreate many of the specialized models in actuarial literature.  Consider adding `BarnettZenwirth`  based on [their paper](https://www.casact.org/library/00pcas/barnett.pdf).

In addition to `origin` and `development` they treat the `valuation` axis as a critical input to their regression model.  This requires including all three time axes in the Triangle long format. I think that's all that is needed to replicate the deterministic aspects of their model.

`TweedieGLM` and this one, should optionally refer to `statsmodels` package if its available since it produces parameter uncertainty estimates. Maybe even consider `statsmodels` as a requirement since most actuaries are likely to have it installed anyway.

**Comment by mlbugs** [comment]
Haven't used statsmodels much but I believe H2O is an alternative
dependency worth considering for this capability.  It can produce
uncertainty estimates for GLM's and has a robust ML library, whereas
statsmodels is limited to, well, statistical models.

**Comment by jbogaardt** [comment]
Thanks mlbugs.  Given the complexity of the library (runs of the JVM), it may not be worth making it a hard dependency, but it seems H2O follows the sklearn API at least somewhat, so we can aim for compatibility with it. I still need to get more familiar with how it works.
