### ISSUE TITLE
Incompatible with sparse 0.12.0

### ISSUE THREAD

**Issue by dipplestix** [casact/chainladder-python#138]
When running 

```
cl.load_sample('clrd')
```

yields "IndexError: arrays used as indices must be of integer (or boolean) type"

Fixed by downgrading to sparse--0.9.1

**Comment by jbogaardt** [comment]
This along with #122 can be covered by better CI pipeline.  I think the [xarray](https://github.com/pydata/xarray) project has a similar, but far more robust setup that we can emulate.  They are using github actions, pytest, and conda environments - same as chainladder.
