### ISSUE TITLE
cl.DevelopmentConstant.ldf_ and .cdf_ attributes not implemented

### ISSUE THREAD

**Issue by dusiod** [casact/chainladder-python#141]
`cl.DevelopmentConstant({12.0: 1.2, 24.0: 1.1, 36.0: 1.5}).ldf_`

_Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'DevelopmentConstant' object has no attribute 'ldf_'_

proposed solution:
```
                pattern = cl.DevelopmentConstant({24.0: 1.2, 12.0: 1.1, 36.0: 1.5}).patterns
                ata = [x for _, x in sorted(zip(pattern.keys(), pattern.values()))]
                atu = list(np.cumprod(ata[::-1])[::-1])

```

**Comment by jbogaardt** [comment]
Hi @dusiod .  

These attributes show up once you invoke the `fit` method. For example:
```python
cl.DevelopmentConstant({12.0: 1.2, 24.0: 1.1, 36.0: 1.5}).fit(any_random_triangle).ldf_
```
This is necessary to make the estimator conform to the same API as all other estimators.  Refer to the [Parameter Types](https://chainladder-python.readthedocs.io/en/latest/modules/development.html#parameter-types) section of the docs where fitted attributes (like `ldf_`) vs hyperparameters are discussed.

**Comment by dusiod** [comment]
Understood, thank you for the clarification
