### ISSUE TITLE
cl.DevelopmentConstant.fit() method fails with a one diagonal triangle

### ISSUE THREAD

**Issue by goduckie** [casact/chainladder-python#146]
Use case: only latest figures available, to be development to ultimate using some pattern, e.g. industry

```
import chainladder as cl

#get data
tri_name = 'ukmotor'
tri_data = cl.load_sample(tri_name).latest_diagonal.to_frame(keepdims=True).reset_index()

#create triangle
tri = cl.Triangle(data=tri_data, origin='origin',development='development', columns='values')

#create dev_constant
dev_constant = cl.DevelopmentConstant(patterns={d:1 for d in range(12, 12*(len(tri_data.origin)+1),12)}, style='ldf')

#combine
dev_constant.fit(tri)
```

#error
#ValueError: Slice returns empty Triangle

Is there an issue with the package or the above code? Or should / can this scenario be approached differently?

**Comment by jbogaardt** [comment]
Two things are happening here.

1. The `tri_data` dataframe doesn't have a 'development' column. I think the intent here is to use the 'valuation' column.  I'll be the first to admit that when creating triangles (which only accept valuation-like entries for development) the argument should be called `valuation` and not `development`.  Regardless, if you try this it should create the triangle you intend:
```python
tri = cl.Triangle(data=tri_data, origin='origin',development='valuation', columns='values')```
```
2. As a single valuation vector, the triangle is smart enough (or dumb enough) to coerce itself to a valuation triangle since there is only one valuation and that is a more compact/ideal format. However almost none of the estimators want a triangle expressed as a valuation triangle.  No worries, you can simply force it to be a development triangle.  Try:
```python
tri = cl.Triangle(data=tri_data, origin='origin',development='valuation', columns='values').val_to_dev()
```
From there, I think the rest of your code should work as expected.

**Comment by goduckie** [comment]
Hello,  trying my hardest to break it =]  Thank you for clarifying this, forcing it to .val_to_dev() was not obvious, but it worked.  and the second code snippet resolves the issue.

`tri = cl.Triangle(data=tri_data, origin='origin',development='valuation', columns='values').val_to_dev()`

Is there any downside to including this method call within the estimators, to ensure the triangle is in the required format? 

However, I'm not sure what you mean by the first comment, as I'm seeing a development column (not a valuation column) in tri_data. Output below:

`tri_data = cl.load_sample(tri_name).latest_diagonal.to_frame(keepdims=True).reset_index()
`

            tri_data
               Total     origin                   development   values
            0  Total 2007-01-01 2013-12-31 23:59:59.999999999  12690.0
            1  Total 2008-01-01 2013-12-31 23:59:59.999999999  12746.0
            2  Total 2009-01-01 2013-12-31 23:59:59.999999999  12993.0

**Comment by jbogaardt** [comment]
> Is there any downside to including this method call within the estimators, to ensure the triangle is in the required format?

Not really, each triangle has an `is_val_tri` property that can be checked and used to coerce to the desired format.  The only downside I see is that it is work that someone has to do. It's a good first issue, and we/I gladly accept Pull Requests if you're interested.

As for the first comment, you must be on an older version of chainladder and the functionality is unintended, meaning it is unsupported and subject to change. Here's what I see:
```python
>>> import chainladder as cl
>>> tri_name = 'ukmotor'
>>> cl.load_sample(tri_name).latest_diagonal.to_frame(keepdims=True).reset_index().head()
   Total     origin                     valuation   values
0  Total 2007-01-01 2013-12-31 23:59:59.999999999  12690.0
1  Total 2008-01-01 2013-12-31 23:59:59.999999999  12746.0
2  Total 2009-01-01 2013-12-31 23:59:59.999999999  12993.0
3  Total 2010-01-01 2013-12-31 23:59:59.999999999  11093.0
4  Total 2011-01-01 2013-12-31 23:59:59.999999999  10217.0
>>>
>>> cl.__version__
'0.8.3'
```

**Comment by goduckie** [comment]
Yes, it was a version issue, updating to 0.8.2 replicates your output. 

I'll take a look under the hood to see where` .val_to_dev()` should be incorporated.

**Comment by jbogaardt** [comment]
Off the top of my head, doing something similar to [validate_X](https://github.com/casact/chainladder-python/blob/master/chainladder/methods/base.py#L18-L24) but in `DevelopmentBase`.
