### ISSUE TITLE
cl.Pipeline fails with pd.util.hash_pandas_object

### ISSUE THREAD

**Issue by goduckie** [casact/chainladder-python#148]
Issue: class object pipeline cannot be hashed, as per example below. This error is not encountered with cl.Development, cl.Chainladder 

Minor question: Any particular reason why steps are a list of tuples rather than a dict?  Would make querying / subsequent updates easier.

```
            import chainladder as cl
            steps = [
                ('sample', 'passthrough'),
                ('dev', cl.Development(average='volume')),
                ('tail', cl.TailCurve('exponential')),
                ('model', cl.Chainladder())]


            #cl.Development - ok
            df = pd.DataFrame(pd.Series({'cl':steps[1][1]}))
            pd.util.hash_pandas_object(df, index=True)

            #cl.model - ok
            df = pd.DataFrame(pd.Series({'cl':steps[3][1]}))
            pd.util.hash_pandas_object(df, index=True)

            #cl.pipeline - FAIL
            pipe = cl.Pipeline(steps=steps)
            df = pd.DataFrame(pd.Series({'cl': pipe}))
            pd.util.hash_pandas_object(df, index=True)
```

**Comment by jbogaardt** [comment]
Hi @goduckie,

This doesn't work for the same reason it doesn't work for scikit-learn. 
```python
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

# sklearn.Pipeline FAIL
pipe = Pipeline(
    steps=[('pca', PCA()),
           ('model', LinearRegression())]
)
df = pd.DataFrame(pd.Series({'cl': pipe}))
pd.util.hash_pandas_object(df, index=True)
```

`cl.Pipeline` inherits from the `sklearn.Pipeline` and other than actuarial-specific enhancements, we make no attempt to alter the underlying structure of the sklearn class.  If you think the `Pipeline` should be hashable then it would probably be better opened as an issue with sklearn.  

The list of tuples approach is sklearn too, and so we won't deviate from how they do it.  However, the estimator has a `named_steps` property that gives you dictionary-like access to the individual steps.

```python
# Can access like this:
pipe.named_steps.model
# or this:
pipe.named_steps['model']
```

**Comment by goduckie** [comment]
Thanks John,  will open it with them.   Consistent behavior eases the pain...  if not for me then at least for someone in the future. ;) Will use your example from above.
