### ISSUE TITLE
Edge case - developing a 'triangle' with only one entry

### ISSUE THREAD

**Issue by goduckie** [casact/chainladder-python#158]
Appreciate this is an elaborate way multiplying a single number by a factor/factors, but nevertheless do not think the method should fail.  

Example below:

```
#triangle with one entry
data = pd.DataFrame({'origin':2014, 'valuation_date':'01.01.2021', 'amount':100}, index=[1])
tri = cl.Triangle(data, origin='origin',development='valuation_date',columns='amount')

#create a development constant                    
dev_periods = cl_tri.val_to_dev().development.to_list()
kwargs = {'patterns': {k: 1.5 for k in dev_periods}, 'style': 'ldf_'}
cl_dev_constant = cl.DevelopmentConstant(**kwargs)

#fit - fail
cl_dev_constant_fit = cl_dev_constant.fit(cl_tri.val_to_dev())

# aim
cl.Chainladder().fit(cl_dev_constant_fit.transform(tri)).ultimate_

```

Adding a second 'origin' row to the triangle resolves the issue, so looks to be related to the one entry triangle only.

**Comment by jbogaardt** [comment]
I'm suprised you can even create a one entry triangle like this.  There are so many ambiguous properties when only one cell is present.
1. What is the grain of the origin? Year, Month?
2. What is the grain of the development? Year, Month?
3. Is the triangle cumulative or incremental?
4. Is it a valuation triangle or a development triangle?

These properties are assumed to be known with reasonable certainty. If they are not, then most of the library will fail, not just this example.  In this particular case, the `link_ratio` property cannot be determined, and `DevelopmentConstant` uses that to come up with pattern labels. 

I think the edge case here is that you are able to produce a single cell triangle, and this should be disallowed.

**Comment by goduckie** [comment]
I strongly disagree with the last comment, as:

- disallowing this would invalidate legitimate use cases eg:
    - cannot apply to new lines of business, 
    - a portfolio transfer / purchase, where we know the pattern (development constant) but only have one period of development
     - a new event or type of event loss that needs to be dealt with separately

- all the questions posed can be answered through parameterization of the relevant classes, so there is no ambiguity here as these do not have to be inferred.

-  There is no mathematical / technical reason why this should not work. It could be a limitation of the implementation, but that is still amounts to an issue. 


What do you mean by 'DevelopmentConstant uses that to come up with pattern labels.' ? bc these are already specified in the parameterization    

```
kwargs = {'patterns': {k: 1.5 for k in dev_periods}, 'style': 'ldf_'}
cl_dev_constant = cl.DevelopmentConstant(**kwargs)
```

**Comment by jbogaardt** [comment]
I'm suggesting disallowing for a single origin/single development triangle.  Having a single development with more than one origin period is allowable as you already pointed out.  I wouldn't think this would affect LPTs.  For new lines it would at most mean waiting to the end of the second month.  

> * There is no mathematical / technical reason why this should not work. It could be a limitation of the implementation, but that is still amounts to an issue.

I don't disagree and as always am open to PRs. But, given the broader needs in package, this one doesn't rise to the top of my personal list of priorities for the package. 

> What do you mean by 'DevelopmentConstant uses that to come up with pattern labels.' ? bc these are already specified in the parameterization

I mean `cl_tri` fails on `X.link_ratio` which is referenced in `DevelopmentConstant`. If `link_ratio` works for single cell Triangles, then I suspect your example would have worked.  To keep the code reasonably DRY, we borrow some properties of `link_ratio` when building estimators of development patterns.

**Comment by goduckie** [comment]
_Disallowing single origin / single development triangles_ 
- again very much disagree, and hope this package doesn't go the route of restricting functionality that doesn't work as expected, particularly when there are legitimate use cases & no mathematical / technical reasons as to why it shouldn't work.

_"at most mean waiting to the end of the second month."_
- that really depends on your market, in some cases Bordeaux are only produced quarterly or even less often. In any case that's not something most bosses / stakeholders will take as an excuse... ;)  

_"I mean cl_tri fails on X.link_ratio which is referenced in DevelopmentConstant"_
- will see if I can propose a solution

**Comment by jbogaardt** [comment]
Fair enough @goduckie..sounds like you work in reinsurance. The nice thing about open source is that you can improve the things that matter most to you, but also leverage things that matter most to others.  I very much look forward to your contributions.

**Comment by jbogaardt** [comment]
One entry triangles are supported now and this example no longer fails (on master). This will get into release `0.8.11`:
```python
import chainladder as cl
import pandas as pd

#triangle with one entry
data = pd.DataFrame({'origin':2014, 'valuation_date':'01.01.2017', 'amount':100}, index=[1])
cl_tri = cl.Triangle(data, origin='origin',development='valuation_date',columns='amount', cumulative=True)

#create a development constant                    
dev_periods = cl_tri.val_to_dev().development.to_list()
kwargs = {'patterns': {k: 1.5 for k in dev_periods}, 'style': 'ldf_'}
cl_dev_constant = cl.DevelopmentConstant(**kwargs)

#fit - this now works
cl_dev_constant_fit = cl_dev_constant.fit(cl_tri.val_to_dev())

# aim
cl.Chainladder().fit(cl_dev_constant_fit.transform(cl_tri)).ultimate_
```
