### ISSUE TITLE
CaseOutstanding.full_expectation_

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#159]
The `full_expectation_` currently replicates the known triangle, `X` for its inner diagonals.  It needs to produce estimated inner diagonals based on the method fit.

**Comment by kennethshsu** [comment]
I am going to try to fix this one.

**Comment by kennethshsu** [comment]
Does CaseOutstanding currently even have `full_expectation_` or `full_triangle_`?

In fact, do you remember if `cl.CaseOutstanding
()` is fully implemented? There's not even an `ultimate_`. According to the [paper](https://www.casact.org/sites/default/files/database/studynotes_friedland_estimating.pdf), page 265 (or 271 by count), there are two methods, did we do both? There are a lot of useful attributes already implemented though.

It'll be helpful if you can provide some sample code.

**Comment by kennethshsu** [comment]
Looking at this more, I don't think the method is implemented correctly. 

I am trying to reconcile the example in the [paper](https://www.casact.org/sites/default/files/database/studynotes_friedland_estimating.pdf), starting page 270.

```python
import chainladder as cl
usauto = cl.load_sample('usauto')

# Case outstanding
usauto["incurred"] - usauto["paid"]

# Incremental paid
usauto["paid"].cum_to_incr()
```

In the paper, the selected LDFS are the latest 3, simple average, I actually think the below code does not do simple average, but volume weighted. But either way, the result is weird.
```python
model = cl.CaseOutstanding(paid_to_incurred=('paid', 'incurred'), paid_n_periods = 3, case_n_periods = 3).fit(usauto)

# Paid to prior case triangle - this is good!
model.paid_to_prior_case_ 
# Selected paid to prior case LDFs - weird numbers?
model.paid_ldf_
# Case oustanding to previous case outstanding triangle - this is good!
model.case_to_prior_case_
# Selected case to prior case LDFs - weird numbers?
model.case_ldf_
```

Can you confirm that I am doing this right?

**Comment by jbogaardt** [comment]
I think you're correct. The `paid_n_periods` and `case_n_periods` arguments aren't working correctly. Omiting them produces reasonable answers for the `ultimate_`:

```python
pipe = cl.Pipeline(steps=[
    ('dev', cl.CaseOutstanding(paid_to_incurred=('paid', 'incurred'))),
    ('model', cl.Chainladder())
])
pipe.fit(usauto).named_steps.model.ultimate_['paid']
```

**Comment by kennethshsu** [comment]
Ok, let me try to fix this one.

**Comment by jbogaardt** [comment]
Feel free to make it a separate issue for tracking purposes.

**Comment by kennethshsu** [comment]
Let me try to reorganize this thread and I think we can split this into three separate issues:

1. Expectation calculation, this is the original issue on the thread
2. Implementing [method 2](https://www.casact.org/sites/default/files/database/studynotes_friedland_estimating.pdf) as presented by Friedland, page 265 (or 271 by count)
3. A bug in the calculation of the LDFs as presented in the paper

I will make 3 separate tickets so we can better track them.

**Comment by kennethshsu** [comment]
Now in #281, #282, and #283.

I think we can close this one for now.
