### ISSUE TITLE
Triangles with iloc() giving me unintuitive result?

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#170]
```
triangle = cl.load_sample('clrd')
triangle.loc['Allstate Ins Co Grp']['CumPaidLoss']
triangle.loc['Allstate Ins Co Grp'].iloc[1]['CumPaidLoss']
```

The above code actually filters only Allstate data (as expected), which we are left with "wkcomp" and "prodliab", "wkcomp" comes first, but with subseting with ```.iloc[1]```, we actually get the "wkcomp" data instead of "prodliab", the indexes are flipped. Tried this with a few other companies, couldn't replicate the issue, did I do something wrong?

**Comment by jbogaardt** [comment]
Having a hard time replicating the issue. The index for the clrd triangle is sorted alphabetically. Limiting to just `triangle.loc['Allstate Ins Co Grp']` retains the alphabetical order of the LOBs and 'wkcomp' is at the second index (`iloc[1]`) as I would expect.

**Comment by kennethshsu** [comment]
In the raw data, "wkcomp" is listed above "prodliab" though? Are you saying when the data is loaded into the triangle format, the segments get sorted alphabetically?

**Comment by jbogaardt** [comment]
Ah I see. I haven't noticed that before.  There are a few pandas operations that will sort an index, `groupby` is one of them. As part of Triangle instantiation, we call a pandas `groupby` to guarantee we do not have duplicate entries on the triangle index. Pandas supports having duplicates in the index, but the Triangle does not. 

```python
import chainladder as cl
# Create dataframe in reverse-alphabetical order
df  = cl.load_sample('clrd').dev_to_val().to_frame().reset_index().fillna(0).iloc[::-1]

df.groupby(['GRNAME', 'LOB'])['CumPaidLoss'].sum() # Pandas re-sorts alphabetically
``` 

Aggregating the duplicates is a problem for achieving parity with pandas.  During the initial phases of the project, it was easier to write the triangle arithmetic logic without duplicate support and this has never been refactored.  What you're witnessing is a symptom of that.

**Comment by kennethshsu** [comment]
Got it, that makes sense, I will make a note in the tutorial as I try to improve the documentation. I think it's fine that the data gets sorted, we just need to warn the users.
