### ISSUE TITLE
Add slack app to github repo

### ISSUE THREAD

**Issue by pdavidsonFIA** [casact/chainladder-python#184]
Not so much an issue as much as a repo config request.
Slack can be integrated to github repos so you can subscribe to notifications:
https://slack.github.com/

**Comment by pdavidsonFIA** [comment]
hi @jbogaardt it's just another mechanism for notifications.
I use slack and there is a github bot through which I can subscribe to whichever repos I want.

github notifications are fine but I think that just pings emails.

I think there is no requirement for you to do anything with Slack, it's just a repo feature that is useful to some.

**Comment by jbogaardt** [comment]
@pdavidsonFIA , let me know if this didn't work:
https://join.slack.com/t/chanladder-python/shared_invite/zt-ueynt387-_i6ZC2P62mlIB4XZxv6p5w

**Comment by jbogaardt** [comment]
I see a comment in slack from @mlbugs, so this appears to be working now.
