### ISSUE TITLE
link_ratio() should null out values and consider "W_"

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#190]

**Comment by jbogaardt** [comment]
This can either be done in the `link_ratio` or in `w_` itself, though I think it is preferable in `w_`.

**Comment by jbogaardt** [comment]
Consider `from chainladder.utils.utility_functions import num_to_nan` which is a function that converts 0s in an array to nans and supports the different arrray backands of chainladder (sparse, numpy, cupy)
