### ISSUE TITLE
heatmap() should utilize a diverging color spectrum and use ranking instead of percentile

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#191]
Diverging color is better so we can see which values are above or below the medium LDF
Using ranking instead will force the display to have half the LDFs being high (or "hot"), and half being low (or "cold")

**Comment by jbogaardt** [comment]
Resolved by #194

**Comment by jbogaardt** [comment]
I think we need to rework this one.  The argument `gmap`  is only available in pandas 1.3 and later.  Chainladder currently supports pandas>=0.23.  Many environments are not yet on pandas==1.3.  For example google colab is on 1.1.5 and when installing chainladder, it doesn't force a reinstall of pandas == 1.3.
