### ISSUE TITLE
drop_high and drop_low in cl.Development() should allow the user to drop more than just the highest value

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#192]

**Comment by jbogaardt** [comment]
The main thing we need to be careful of here is that this is an enhacement and existing functionility should either continue to be honored forever or it should follow a deprecation cycle until at least v0.9.0.

**Comment by kennethshsu** [comment]
Agree with that, we can continue to accept an array of Booleans or an array of non-negative integers (with 0 indication not dropping any values).

Do we always check user input?

**Comment by jbogaardt** [comment]
It is good practice to validate user input, though we don't do it as thoroughly as we should. The goal of #127 is to design a common API for accepting a vector of assumptions across all estimators. As it stands, that issue is still open.

**Comment by jbogaardt** [comment]
It is also worth pointing out that we want scikit-learn compliant esitmators.  Under their developer guide they have rules on instantiation that we should continue to honor.
https://scikit-learn.org/stable/developers/develop.html#instantiation

Specifically, any logic that validates/standardizes user inputs should happen during `fit` and not `__init__`.

**Comment by kennethshsu** [comment]
I want to bring this thread back to live.

I was thinking drop_high can either be boolean, or an integer. If it's True in boolean form, it is simply 1, or drop the highest value. Once we have validated the input, we then convert it into an array. Then the next natural extension is to accept an array with varying `drop_high` for the various age-to-age factor calculation.

**Comment by jbogaardt** [comment]
That is a good suggestion. I like it.

**Comment by kennethshsu** [comment]
I also think the array of boolean doesn't work currently, even though the doc says it does?

```python
import pandas as pd
import numpy as np
import chainladder as cl
import os

%load_ext lab_black
%matplotlib inline

raa_df = pd.read_csv(
    "https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/raa.csv"
)
# raa_df.head(5)
raa = cl.Triangle(raa_df, origin="origin", development="development", columns="values")
raa.link_ratio.heatmap()
cl.Development(
    drop_high=[
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
    ]
).fit(raa).ldf_
```

**Comment by jbogaardt** [comment]
I can't seem to replicate the error you describe:
```python
>>> import chainladder as cl
>>> print(cl.__version__)
0.8.9
>>> raa = cl.load_sample('raa')
>>>
>>> # Does List of bools behave the same as a single bool?
>>> (cl.Development(drop_high=[True]*9).fit(raa).ldf_ ==
...  cl.Development(drop_high=True).fit(raa).ldf_)
C:\Users\jbogaard\Miniconda3\lib\site-packages\chainladder\development\base.py:103: UserWarning: drop_high and drop_low cannot be computed when less than three LDFs are present, exclusions are ignored.
  warnings.warn(
True
>>>
>>> # Does a Manually calculated drop_high for first period match the estimnator?
>>> age_12_24 = raa[(raa.origin!='1982')].iloc[..., :-1, :2]
>>> age_12_24.sum().link_ratio == cl.Development(drop_high=[True] + [False]*8).fit(raa).ldf_.iloc[..., 0]
True
```

**Comment by kennethshsu** [comment]
Maybe I messed something up when I was playing with it :(

**Comment by kennethshsu** [comment]
Need some help with the new warning message. 

What I have so far `Exclusion is ignored for some age-to-age factor when the selected exclusion result in the number of remaining factors being less than the minimum age-to-age data required (default preserve = 1).")` I don't really think it's clear, and it's very wordly. Thoughts?

**Comment by jbogaardt** [comment]
Idk, more about the what, less about the why?:
```python
'''Some exclusions in link ratios have been ignored. At least {} link ratio(s) required for ldf_ estimation'''.format(preserve)
```

**Comment by kennethshsu** [comment]
Cool, will use that!

**Comment by kennethshsu** [comment]
Should have a new PR pretty soon :)
