### ISSUE TITLE
TailCurve()

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#198]
Should extend beyond 1 year, a common use case would be to know the annual IBNR runoff beyond the triangle

**Comment by jbogaardt** [comment]
Added `tail_duration` to each tail estimator. Default is 12 (months), but could be any annual interval beyond that (24,36,...).  Not too fond of the name, but don't know what else to call it - shout if you have suggestions.

**Comment by kennethshsu** [comment]
Agree that `tail_duration` is not the best. How about `tail_extention`?

**Comment by jbogaardt** [comment]
Another alternative: `projection_period`
