### ISSUE TITLE
TailCurve()'s fit_period improvement

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#200]
It's not clear what the fit_period does, apparently data beyond the `fit_period` is used to fit the tail
An improvement idea is to take an array instead, for example, if we want to use age 12, 24, 48, 60 (without age 36) to fit the tail. This is currently not possible.

**Comment by jbogaardt** [comment]
Yep, I definitely don't like how `fit_period` works, but we should either retain it while bringing on better approaches, or follow a deprecation cycle.
