### ISSUE TITLE
Ultimate timestamp is currently set to 2261-12-31 23:59:59.999999999

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#201]
The latest timestamp is currently set to 2261-12-31 23:59:59.999999999, but it's the latest possible time is now revised as 9999-12-31 23:59:59.999999999

```
from datetime import date, time, datetime

datetime.max
```

**Comment by jbogaardt** [comment]
This probably creates backward compatibility issues with pandas (supported from 0.23.0 and later) and so we would want to follow a deprecation cycle.  An alternative without deprecation is to keep the default as is, but allow the end user to modify the setting.  As we gain more and more package-wide settings, we might want to create an `cl.options` dictionary, similar to how pandas does `pd.options`.

**Comment by jbogaardt** [comment]
Borrowing from `pd.options` design, I've added `cl.options`.  From here the user can configure package level settings including the ultimate valuation date.

```python
>>> import chainladder as cl
>>> cl.options.get_option('ULT_VAL')
'2261-12-31 23:59:59.999999999'
>>> cl.options.set_option('ULT_VAL', '2030-12-31 23:59:59.999999999')
>>> cl.options.get_option('ULT_VAL')
'2030-12-31 23:59:59.999999999'
>>> cl.options.reset_option()
>>> cl.options.get_option('ULT_VAL')
'2261-12-31 23:59:59.999999999'
```
