### ISSUE TITLE
Data being Mutated

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#213]
Executing the following lines a few times and you would eventually get some unexpected results.

```python
prism = cl.load_sample("prism")
prism = prism.incr_to_cum()
prism["Capped 100k Paid"] = cl.minimum(prism["Paid"], 100000)
prism["Excess 100k Paid"] = prism["Paid"] - prism["Capped 100k Paid"]
prism["Excess 100k Paid"].sum().grain("OYDY")
````

**Comment by kennethshsu** [comment]
What version pandas are you on? 

Assuming that you are on chainladder 0.8.9, I am getting a new error `'Triangle' object has no attribute 'data'` when I get that `cl.minimum` function.

**Comment by jbogaardt** [comment]
Yah, there was a bug in `cl.minimum` it that has been fixed on the master branch.
