### ISSUE TITLE
Docs revamp

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#214]

**Comment by jbogaardt** [comment]
I've created a set of docs using [Jupyter Book](https://jupyterbook.org/intro.html) and hosted them here:
https://chainladder-python.readthedocs.io/en/latest

@kennethshsu , let me know what you think.

The docs are basically the same, with an updated theme, but now we have a lot more styling options through Jupyter Book.  Additionally, we can move away from `rst` files which are quirky to write and are not automatically executed. Authoring content in jupyter notebooks is much easier.

Jupyter Book is a very clean interface with a lot of styling options. One thing that is evident with the new format is that the docs are somewhat all over the place. Specifically, the user guide and tutorials have a high degree of overlap.  I think it would be better if the tutorials and user guide were combined into the user guide.  Then, a "Getting Started" tutorial that is much lighter on content - like a 10 minute intro. The User Guide could then be really fleshed out with lots of detail, almost like a course or a book.

We use `sphinx_gallery` for our example gallery. I got it to work with Jupyter Book, but all autogenerated content is `.rst` which 
We may want to write some small scripts to make a more Jupyter Book friendly gallery.  In either case, it looks comparable to the original docs - it's not so polished, but works just fine.

Overall, I am pleased with what Jupyter Book can do and now that we have a working base of docs on readthedocs.io it should be a smooth/pleasant process of updating docs to a more modern feel.

**Comment by kennethshsu** [comment]
I like it a lot! This looks really good! Love the great new logo too!

After poking around the site for a bite, noticed a few issues though:
- Installation probably should be step 1 under Getting Started?
- This is not friendly with the linter `black`, lots of errors thrown.
- The font size of the result after each code block execution is too large.
- We still need to unify how we show the code and results, sometimes we use the traditional code block, but other times we use ">>>" then the result.

Will try to think of more...!

**Comment by jbogaardt** [comment]
> * Installation probably should be step 1 under Getting Started?

That makes sense. Still a lot to do.


> * This is not friendly with the linter `black`, lots of errors thrown.

This should be resolved. Needed to add the dependencies to `environment-docs.yaml`


> * The font size of the result after each code block execution is too large

Yah, I'm sure there is a setting for this. There is a lot of "modern" functionality in jupyter-book that we just aren't using yet. It's worthwhile to skim its docs.


> * We still need to unify how we show the code and results, sometimes we use the traditional code block, but other times we use ">>>" then the result.

This should be resolved too. We should move away from ">>>". This gets fixed when converting the `rst` files to `ipynb`
