### ISSUE TITLE
Issue on page /library/install.html (Python 3.10 support)

### ISSUE THREAD

**Issue by DKSpurs** [casact/chainladder-python#240]
Hi,

I have been unable to install Chainladder via pip or conda. 

I have tried updating PIP (removed anaconda) and all other debugging but still not able to install the chainladder package.

All other PIP based packages have installed fine.

Attached the CMD error - any help is greatly appreciated.
[Chainladder_pip_error.txt](https://github.com/casact/chainladder-python/files/7793942/Chainladder_pip_error.txt)

PS not sure if this is the right channel but I could not find any other communication channels

Thanks

**Comment by jbogaardt** [comment]
I think the issue is python 3.10 has some compatibility issues for llvmlite (on which chainladder indirectly depends).  For now, chainladder is only supported through the python 3.9 series.

**Comment by DKSpurs** [comment]
Thanks John. Will revert to an older version of Python and use that
