### ISSUE TITLE
Requirement - Dropping Link Ratios conditionally (based on any input value) 

### ISSUE THREAD

**Issue by muhammadshamsherkhan2002** [casact/chainladder-python#242]
Hi! I hope that you all are fine.

There are several arguments for dropping/discarding problematic link ratios as well as excluding whole valuation periods or highs and lows. Any combination of the ‘drop’ arguments is permissible.

I would like to ask you that is there any provision/function (in chainladder-python library) to drop link ratios conditionally (based on any input value), please guide me in this regards. Please go through the example below (which we need):

**Example:**
This is sample link ratio:

**### Source - Link Ratio (before applying any dropping condition)**
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|**
    **| 2017Q1 |** 1.7566 | 1.1415 | 1.0917 | 1.0091 | 1.0062 | 1.0007 | 1.0014|
    **| 2017Q2 |** 1.9576 | 1.2615 | 1.0640 | 0.8965 | 1.0008 | 1.0029 |  
    **| 2017Q3 |** 2.4820 | 0.9930 | 1.0588 | 1.0491 | 1.0121 |  
    **| 2017Q4 |** 1.8434 | 1.0787 | 1.0773 | 0.9654 |  
    **| 2018Q1 |** 1.4951 | 0.9120 | 1.0428 |  
    **| 2018Q2 |** 2.3292 | 1.1350 |  
    **| 2018Q3 |** 1.1851 |

**Link Ratio-Cuttoff (input value):  0.9999** 

**Our requirement is that:** If any value of above 'Source - Link Ratio' is getting less than 'Link Ratio-Cuttoff (input value)', the particular value will be dropped as mentioned in the below 'Target - Link Ratio'.
 
**### Target - Link Ratio (After applying condition based on the above input value)**
    **&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|**
    **|&nbsp;2017Q1&nbsp;|**&nbsp;1.7566&nbsp;|&nbsp;1.1415&nbsp;|&nbsp;1.0917&nbsp;|&nbsp;1.0091&nbsp;|&nbsp;1.0062&nbsp;|&nbsp;1.0007&nbsp;|&nbsp;1.0014&nbsp;|
    **|&nbsp;2017Q2&nbsp;|**&nbsp;1.9576&nbsp;|&nbsp;1.2615&nbsp;|&nbsp;1.0640&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;1.0008&nbsp;|&nbsp;1.0029&nbsp;|  
    **|&nbsp;2017Q3&nbsp;|**&nbsp;2.4820&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;1.0588&nbsp;|&nbsp;1.0491|&nbsp;1.0121&nbsp;|  
    **|&nbsp;2017Q4&nbsp;|**&nbsp;1.8434&nbsp;|&nbsp;1.0787&nbsp;|&nbsp;1.0773&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  
    **|&nbsp;2018Q1&nbsp;|**&nbsp;1.4951&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 1.0428 |  
    **|&nbsp;2018Q2&nbsp;|** 2.3292 | 1.1350 |  
    **|&nbsp;2018Q3&nbsp;|** 1.1851 |

I have made many tries to explore particular subjective dropping/omitting link-ratio feature in the provided chainladder-python documentation. However, I was unable to find out this. You are kindly requested to guide me in this regard, if feature is already available.

If it is not available and if it is possible, please provide the following conditional dropping link ratio feature at your earliest.

Best Regards,
Muhammad Shamsher Khan

**Comment by jbogaardt** [comment]
Hi @muhammadshamsherkhan2002, thanks for the insightful feature request. You are correct, it does not currently exist and it would be a good feature to add.

**Comment by kennethshsu** [comment]
I was thinking about this the other day.

Would you need to have an array of (different) conditions for each of the ages? E.g. >0.9 for age 12-24, >0.95 for age 24-36, etc? Or just one condition that applies to the whole series? 

Either way I don't think it'll be too difficult to get this in.

**Comment by jbogaardt** [comment]
My vote is for maximizing flexibility while minimizing complexity. That's usually easier said than done. API design is hard which is why we borrow so much from the brilliance of pandas and scikit-learn. Were you thinking of tackling this one @kennethshsu?

**Comment by muhammadshamsherkhan2002** [comment]
**Dear Kenneth S. Hsu,**
Currently, our requirement is that one condition to be applied on whole series (means: whole link ratio). However, maximum flexibility should be available in the API.

**One thing more:** I described my requirement above with example that (link ratio value less than (<) the 'Link Ratio-Cuttoff (input value)'). Please remember that it could be vice versa means: greater than (>).

**Comment by kennethshsu** [comment]
Yea of course, agree with you completely.

John, I can try to take this one.🙂 I don't think it'll be much work from the drop high low that improvement that we have.

**Comment by jbogaardt** [comment]
Cool, thanks! On `TailCurve`, we have a similar concept that uses a tuple across all ages:
https://github.com/casact/chainladder-python/blob/master/chainladder/tails/curve.py#L35-L40

Not to say that this is the best solution in this case, but its worth highlighting since as should strive to handle similar concepts in similar ways when we can. Its better for end-user muscle memory.

**Comment by kennethshsu** [comment]
There's a PR open now. Once approved, try the following:
```python
import pandas as pd
import numpy as np
import chainladder as cl

%load_ext lab_black
%matplotlib inline

raa = cl.load_sample("raa")
raa.link_ratio.heatmap()

cl.Development().fit(raa).ldf_

# single float
cl.Development(drop_above=40.0).fit(raa).ldf_

# another single float
cl.Development(drop_above=1.2).fit(raa).ldf_

# using both bounds floats
cl.Development(drop_above=1.2, drop_below=1.05).fit(raa).ldf_

# arrays
cl.Development(drop_above=[40.0], drop_below=[0.0, 0.0, 1.05, 1.7]).fit(raa).ldf_

# another two arrays
cl.Development(drop_above=[40.0], drop_below=[0.0, 0.0, 1.05, 1.2]).fit(raa).ldf_

# ints
cl.Development(drop_above=40).fit(raa).ldf_
```

I still need to write some test cases, but let me know if you can already break the code or if any of the calculations are not correct.

**Comment by kennethshsu** [comment]
There's a PR open now. 

We can now use `drop_above` to discard all LDFs above the specified value(s), i.e. LDFs must be <= `specified_value` (note the equal sign), and `drop-below` to do the same thing for values below (values must be >=).

Once approved, try the following:
```python
import pandas as pd
import numpy as np
import chainladder as cl

%load_ext lab_black
%matplotlib inline

raa = cl.load_sample("raa")
raa.link_ratio.heatmap()

cl.Development().fit(raa).ldf_

# single float
cl.Development(drop_above=40.0).fit(raa).ldf_

# another single float
cl.Development(drop_above=1.2).fit(raa).ldf_

# using both bounds floats
cl.Development(drop_above=1.2, drop_below=1.05).fit(raa).ldf_

# arrays
cl.Development(drop_above=[40.0], drop_below=[0.0, 0.0, 1.05, 1.7]).fit(raa).ldf_

# another two arrays
cl.Development(drop_above=[40.0], drop_below=[0.0, 0.0, 1.05, 1.2]).fit(raa).ldf_

# ints
cl.Development(drop_above=40).fit(raa).ldf_
```

I still need to write some test cases, but let me know if you can already break the code or if any of the calculations are not correct.

**Comment by jbogaardt** [comment]
PR is merged. This will appear in the next release. Thank you @kennethshsu!

**Comment by muhammadshamsherkhan2002** [comment]
I hope that you are fine and perfect.

I would like to inform you that I installed the latest release from the githup and verified the newly provided feature "drop_below" which is not working properly.

I provided the sample **drop_below = 1.743** and executed the command and reviewed result. I came to know that it is dropping the values only from single column rather than whole table. It should be dropped from whole link ratio table where the values getting less than the given value given in **drop_below**. Please go through the attached below image.   

Kindly note that it is also raising the **warning**.

![Chainladder - Drop Link Ratio Issue](https://user-images.githubusercontent.com/18509098/152959995-61b2430f-f0c2-4b15-ae30-92002e1931be.jpg)

**Comment by kennethshsu** [comment]
This behavior is expected, as the warning states: `Some exclusions have been ignored. At least 1 (use preserve = ...) link ratio(s) is required for development estimation.` Because for 12-24 and 24-36, everything is above 1.1743, everything would've been dropped, but they aren't because preserve is set to 1 (as the default).

What are you trying to do? Can you help me understand why you want to drop all of the factors for 12-24 and 24-36? What would you use as your LDFs and CDFs?

**Comment by muhammadshamsherkhan2002** [comment]
Please go through the attached sample sheet **(I put the real example)**, the functionality should be worked in that manner.

Currently, **drop_below** is not working in that manner. 

[Sample-Link Ratio (conditionally dropped).xlsx](https://github.com/casact/chainladder-python/files/8046741/Sample-Link.Ratio.conditionally.dropped.xlsx)

**Comment by kennethshsu** [comment]
Sorry, I miss-read your question. Let me re-answer your question above. Because for all other ages, all the factors are below 1.1743, nothing is dropped because preserve is set to 1 (as the default). 

Looking at your Excel example, does `cl.Development(drop_below=0.9900).fit(your_data).ldf_` not work properly? It's a bit hard to test your example without having the data readily available. 

Look at this example using `raa`:
```python
raa = cl.load_sample("raa")
raa.link_ratio.heatmap()
cl.Development(drop_below=2).fit(raa).ldf_
```

The result ties with what I manually calculated in Excel.

[raa.xlsx](https://github.com/casact/chainladder-python/files/8046882/raa.xlsx)

**Comment by muhammadshamsherkhan2002** [comment]
Ok, let me check. I will come again, if I face any issue. :)

**Comment by muhammadshamsherkhan2002** [comment]
Dear Friends, I hope that you are find and perfect.

Please look into the matter below in picture a runtime waring is appearing while using drop_below & drop_above. Is there any issue or something else?

![image](https://user-images.githubusercontent.com/18509098/154054480-04ccc404-6b59-4de6-b62e-e139fca51713.png)

**Comment by jbogaardt** [comment]
I think the issue here is that this is still pre-release. I expect that upon release of chainladder `0.8.11` these warnings will be silenced.

**Comment by muhammadshamsherkhan2002** [comment]
Ok :)

**Comment by kennethshsu** [comment]
@muhammadshamsherkhan2002 for some reason I can't replicate that warning. Can you post the whole script? This executes cleanly without anything.

```python
import pandas as pd
import chainladder as cl

raa = cl.load_sample("raa")
dev = cl.Development(drop_above=40, drop_below=1.1, preserve=0).fit_transform(raa)
dev.link_ratio
```

**Comment by muhammadshamsherkhan2002** [comment]
**@kennethshsu** I executed same code you mentioned above in your comments. It stills raises the warning. Please go through the image below.

![image](https://user-images.githubusercontent.com/18509098/154623730-cb1b742d-badd-4376-a3ee-cdf4d8a28a06.png)

**Comment by kennethshsu** [comment]
@muhammadshamsherkhan2002 can you try to update your packages?

```sh
conda update --all
```

@jbogaardt can you try to see if you get the same warnings as well?

**Comment by jbogaardt** [comment]
I did see this when reported, but I cannot replicate it again on any of my environments

**Comment by muhammadshamsherkhan2002** [comment]
Thanks friends, after executing the following command, the problem has been resolved.
**conda update --all**

**Comment by kennethshsu** [comment]
Yap this one is done. Merged on [Jan 15, 2022](https://github.com/casact/chainladder-python/issues/242#issuecomment-1013678641).

**Comment by kennethshsu** [comment]
I will try to be better and reference the issue number tag in my PR so we can better track changes as well.
