### ISSUE TITLE
Requirement - Provision required for Inputting whole Link Ratio

### ISSUE THREAD

**Issue by muhammadshamsherkhan2002** [casact/chainladder-python#243]
I hope that you are fine and perfect.

It is good to see that your team provided the many features to accommodate the actuarial team fulfillment in python-chainladder library.

We keep on exploring features from your provided documentation as and when needed and fortunately, most of the things are available in the API.

Nowadays, We are exploring the subjective feature in the API. However, We are unable to find it so far. Our requirement is **(provision for inputting whole modified link ratio for re-processing and generation subsequent methods ldf, cdf and so on...)**, please go through the example below:

-Primarily, we will process triangle, link ratio, ldf, cdf and so on as usual based on the input raw data while using python-chainladder library methods:

**for example:**

**-In 1st attempt**
1. actuarial_df = pd.read_csv("c:/actuarial-data/actuarialData.csv")
2. triangle = cl.Triangle(actuarial_df,origin="origin",development="development",columns="values",cumulative=True)
3. triangle.link_ratio
4. cl.Development(average="volume").fit(triangle).ldf_
5. and so on

**-In 2nd attempt or during re-processing (after necessary modification in the link ratio)**
1. input link ratio (like a triangle) 
    linkRatio_df = pd.read_csv("c:/actuarial-data/linkRatioData.csv")

2. Method required for taking complete link ratio as input
    link_ratio = cl.Triangle(linkRatio_df,origin="origin",development="development")
3. and ldf, cdf and so on...

You are kindly requested to guide me in this regard, if feature is already available. If it is not and if it is possible, please provide the following requirement in your API. We will be very grateful to you.

Best Regards,
Muhammad Shamsher Khan

**Comment by kennethshsu** [comment]
Hi Muhammad,

I don't think I understand your request/question. Are you trying to save the link ratios in a csv, then reusing the pattern later by loading the csv back?

**Comment by muhammadshamsherkhan2002** [comment]
Yes, I will save the generated link ratios in a csv file or other file format. Afterwards, I will do some modification in link ratios (where needed) and reusing it by loading this csv back and generate subsequent things such as ldf, cdf and so on accordingly based on the particular link ratios.

**Comment by jbogaardt** [comment]
The support on this front could be a little more seamless than it is, but here are some suggestions:

The  `DevelopmentConstant` estimator is used for supplying ldf/cdf directly, if you're modifying them and want to use them for developing IBNR, you'll need to use `DevelopmentConstant`:
```python
import chainladder as cl
raa = cl.load_sample('raa')
dev = cl.Development().fit(raa)

# Send to csv, modify in excel - it is a pandas dataframe
dev_as_pd = dev.ldf_.to_frame()

# Rehydrate an Development estimator:
new_dev = cl.DevelopmentConstant(
    patterns=dict(zip(dev_as_pd.columns, dev_as_pd.values[0])),
    style='ldf')
```

If you're comfortable modifying the link-ratios in place you can do that too. Keep in mind, that modifying the ldf_ without also re-estimating the variablility parameters will lead to false readings when used with the `MackChainladder`:
```python
dev.ldf_.loc[..., '12-24'] = 3.0
# Modifying ldf_ will cascade to cdf_
dev.cdf_
```

You can also serialize the object using pickle or json to move them to other machines. Each chainladder object should have `to_pickle` and `to_json` and can also be brought back in using `cl.read_pickle` and `cl.read_json`

**Comment by muhammadshamsherkhan2002** [comment]
Thanks dear, let me check. If I get stuck then I will contact you again.

**Comment by muhammadshamsherkhan2002** [comment]
I have performed the following steps:
1. Executed the following command for calling link ratio
**&nbsp;&nbsp;genins.link_ratio**

<html>
<body>





&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.1432 | 1.5428 | 1.2783 | 1.2377 | 1.2092 | 1.0441 | 1.0404 | 1.0630 | 1.0177
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.5106 | 1.7555 | 1.5453 | 1.1329 | 1.0845 | 1.1281 | 1.0573 | 1.0865 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4.4485 | 1.7167 | 1.4583 | 1.2321 | 1.0369 | 1.1200 | 1.0606 |   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4.5680 | 1.5471 | 1.7118 | 1.0725 | 1.0874 | 1.0471 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.5642 | 1.8730 | 1.3615 | 1.1742 | 1.1383 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.3656 | 1.6357 | 1.3692 | 1.2364 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.9228 | 1.8781 | 1.4394 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.9533 | 2.0157 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.6192 |  

</body>
</html>

&nbsp;&nbsp;2. exported the link ratio in excel file with the following command:
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genins.link_ratio.to_frame().to_excel('genins_example.xlsx')**

**&nbsp;&nbsp;&nbsp;3. I made some changes manually in the exported link ratio in excel.**

&nbsp;&nbsp;&nbsp;4. After above, I imported the excel with the following command.
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;actuarial_df = pd.read_excel('genins_.xlsx')**

5. I printed link ratio dataframe after changes as:
**actuarial_df.fillna('')**
<html>
<body>


<html>
<body>





&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2001-01-01 | 3.1432 | 1.54281 | 1.2783 | 1.23772 | 1.20921 | 1.04408 | 1.04037 | 1.06301 | 1.01772
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2002-01-01 | 3.51058 | 1.75549 | 1.54529 | 1.13293 | 1.08449 | 1.12811 | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2003-01-01 | 4.44845 | 1.71672 | 1.45826 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   | 1.03686 | 1.12001 | 1.06058 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2004-01-01 | 4.568 | 1.54705 | 1.71178 | 1.07252 | 1.08736 | 1.04708 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2005-01-01 | 2.5642 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 1.36154 | 1.17422 | 1.13831 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2006-01-01 | 3.36559 | 1.63568 | 1.36916 | 1.23644 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2007-01-01 | 2.9228 | 1.8781 | 1.43939 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2008-01-01 | 3.95329 | 2.01565 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2009-01-01 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|


</body>
</html>
6. After that, I called following command which described by you in yours comments above:<br>

&nbsp;&nbsp;&nbsp;&nbsp;**new_dev = cl.DevelopmentConstant(patterns=dict(zip(actuarial_df.columns, actuarial_df.values)),style='link_ratio')**

7. Afterwards, printed link ratio in the particular format:
**new_dev**
**DevelopmentConstant**(patterns={'12-24': array([Timestamp('2002-01-01 00:00:00'), 3.510581680004999,
       1.755492707535318, 1.545286177675639, 1.132926393588209,
       1.084493376926493, 1.128105808090799, nan, nan, nan], dtype=object),
                              '24-36': array([Timestamp('2003-01-01 00:00:00'), 4.448450467630728,
       1.716718021892648, 1.458256724625596, nan, 1.036859805393634,
       1.1200101235979...
       2.015650947697885, nan, nan, nan, nan, nan, nan, nan], dtype=object),
                              '96-108': array([Timestamp('2009-01-01 00:00:00'), nan, nan, nan, nan, nan, nan,
       nan, nan, nan], dtype=object),
                              'Unnamed: 0': array([Timestamp('2001-01-01 00:00:00'), 3.1432004650019,
       1.54280628882954, 1.278298652129566, 1.237719484102476,
       1.209207035558035, 1.044078995323486, 1.040374043370291,
       1.063009145697263, 1.017724725219544], dtype=object)},
                    style='link_ratio') 

My question is that right now, how I will get the link ratios, ldf, cdf printed in normal/chainladder format based on the modification in excel.

I tried to print the ldf with the command as (**new_dev.ldf_** but application gives error).

Your response and guidance will highly be appreciated.

**Comment by muhammadshamsherkhan2002** [comment]
Thanks John for clarification and appreciate you for detail reply.

Please clarify one thing more that in case of choosing pattern 'simple average', the LDFs are calculated based on the link ratios. In this regard, my question is that if the link ratios are given to the API/library from outside the library. What should be done and how done while using library?

My another question that while using 'DevelopmentConstant' to include a set of patterns picked outside of the library, How will we generate the LDFs, CDF, Ultimate, IBNR and so on while using python chainladder library? Please guide me.

Your early response and guidance will highly be appreciated.

**Comment by jbogaardt** [comment]
> Please clarify one thing more that in case of choosing pattern 'simple average', the LDFs are calculated based on the link ratios.

In chainladder, the calculations for simple averages are not actually based on the link ratios. Instead it uses the weighted least squares formulation in Section(2.2) of [BarnettZehnwirth](https://www.casact.org/sites/default/files/database/forum_98fforum_zehnwirth.pdf). Its unusual to me to see someone modify the link ratios directly. A more common pattern is that the actuary selects ldf patterns from a set of link ratios available in the triangle, but link ratios themselves are immutable. Said differently, modifying the link ratios directly is unsupported.


> But when I print the ldfs and cdfs after executing 'DevelopmentConstant' , library gives the particular error.

All estimators in chainladder follow the scikit-learn API. The `ldf_` has a trailing underscore, suggesting it will only exist upon calling the `fit` method.  See the [example in the docs](https://chainladder-python.readthedocs.io/en/latest/development.html#developmentconstant).

> How will we generate the LDFs, CDF, Ultimate, IBNR and so on while using python chainladder library?

Once you have a fitted `DevleopmentConstant`, you can choose an IBNR method to use with it. Consider this complete example:
```python
>>> import chainladder as cl
>>> triangle = cl.load_sample('ukmotor')
>>> patterns={12: 2, 24: 1.25, 36: 1.1, 48: 1.08, 60: 1.05, 72: 1.02}
>>> dev = cl.DevelopmentConstant(patterns=patterns, style='ldf')
>>> # While the estimator is not fit, it has no ldf_
>>> hasattr(dev, 'ldf_')
False
>>> # When you fit it, it will have an ldf_
>>> dev.fit(triangle)
DevelopmentConstant(patterns={12: 2, 24: 1.25, 36: 1.1, 48: 1.08, 60: 1.05,
                              72: 1.02})
>>> dev.ldf_
       12-24  24-36  36-48  48-60  60-72  72-84
(All)    2.0   1.25    1.1   1.08   1.05   1.02
>>> dev.cdf_
        12-Ult    24-Ult    36-Ult   48-Ult  60-Ult  72-Ult
(All)  3.18087  1.590435  1.272348  1.15668   1.071    1.02
>>> # With a fitted DevelopmentConstant, you can couple it with an IBNR method, Chainladder, CapeCod, etc.
>>> cl.Chainladder().fit(dev.fit_transform(triangle)).ibnr_
              2261
2007           NaN
2008    254.920000
2009    922.503000
2010   1738.051240
2011   2782.579516
2012   5697.697750
2013  13702.406210
```

**Comment by muhammadshamsherkhan2002** [comment]
Thanks for your clarification.

Now, I would like to ask you that it is possible to:
**1.** Primarily, generate the triangle and link ratios based on provided raw data by python-chainladder library. **(already available)**
**2.** then export the generated link ratios into csv/excel file. **(already available)**
**3.** then manually drop the link ratios as desired in generated csv/excel file outside the library. **(not available as per my knowledge)**
**4.** then provide the same sheet to any suitable method of the python-chainladder library. **(not available as per my knowledge)**
**5.** then calculate the ldf, cdf, ibnr etc.. based on the no. 4.

I know that you already provided the feature of dropping link ratios currently present in the library. The 2 of the techniques are mentioned below:

**- example:**

**technique 1:**
- dev = cl.Development(drop=[('2002', 12), ('2003', 36), ('2004', 48), ('2006', 24)])
- transformed_triangle = dev.fit_transform(genins)
- transformed_triangle.link_ratio
In above technique, the given periods's link ratios will be dropped.

**technique 2:**
- dev = cl.Development(drop_valuation='2008')
- transformed_triangle = dev.fit_transform(genins)
- transformed_triangle.link_ratio
In above technique, the whole valuation of 2008 (diagonal) will be dropped.

It is a good feature which you provided, but we want to do the same in the file (excel/csv) where complete link_ratio will be showing and we will be manually dropping the values as desired (rather than using above techniques) and then the particular sheet will be given to the library for further processing.

Your response will highly be appreciated in this regard.

**my 2nd question:**
> import chainladder as cl
> triangle = cl.load_sample('ukmotor')
> **patterns={12: 2, 24: 1.25, 36: 1.1, 48: 1.08, 60: 1.05, 72: 1.02}**
> dev = cl.DevelopmentConstant(patterns=patterns, style='ldf')

Could we be able to provide the file (csv or excel) as a patterns in which the ldfs/cdfs will be mentioned (in the following format - sheet is attached) to the cl.DevelopmentConstant? Kindly note that I try to use the file as a pattern but api throws the error. Please guide me that what the problem with the file or I am missing something.

**error is:**
**KeyError: "None of [Int64Index([12, 24, 36, 48, 60, 72, 84, 96, 108], dtype='int64')] are in the [columns]"**


[ldf_example2.xlsx](https://github.com/casact/chainladder-python/files/7879397/ldf_example2.xlsx)

**Comment by jbogaardt** [comment]
Sorry, we will not provide functionality to manage parts of a workflow between chainladder and Excel/Csv in the future.

The `patterns` argument must be a dictionary. 
```python
# This is a dictionary, not a DataFrame or Triangle
patterns={12: 2, 24: 1.25, 36: 1.1, 48: 1.08, 60: 1.05, 72: 1.02}
```
I suspect you're getting a key error from passing in another object like a DataFrame.
