### ISSUE TITLE
large-datasets.ipynb Broken

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#249]
At some point, the [large-datasets.ipynb](https://github.com/casact/chainladder-python/blob/master/docs/tutorials/large-datasets.ipynb) file got broken. I don't know when the latest good commit was. Is there an easy way to find it? Looks like it reverted to the original version at some point... :(

**Comment by kennethshsu** [comment]
@jbogaardt can you take a look at [this](https://github.com/casact/chainladder-python/blob/01da70ab7cdc808fdc700c81326d5b22a528794f/docs/tutorials/large-datasets.ipynb)? I think I did this becuase I use `black`, but I don't think I plot like that (near line 7)😅

**Comment by jbogaardt** [comment]
Thanks, issue is now resolved.
