### ISSUE TITLE
Heatmap - pandas deprecation of .render()

### ISSUE THREAD

**Issue by genedan** [casact/chainladder-python#274]
Can I take a shot at making a pull request? The following code, when run in an interpreter with Pandas 1.4.1 will trigger a deprecation warning (the warning doesn't appear when I tried it in Jupyter):

![image](https://user-images.githubusercontent.com/6165650/158465846-80d5fcac-ca66-49bc-8259-3b12194ece64.png)

https://github.com/casact/chainladder-python/blob/bc8a52b72f2e202335ca48df5192c85ee0306e44/chainladder/core/display.py#L123-L134

I'd like to see if I can make my first contribution, are the steps to 1) change the code 2)  run pytest, and 3) issue the pull request?

**Comment by jbogaardt** [comment]
Yes, that's pretty much how it works. If you forget to run tests, they will run in the  PR. Also, it's good practice to mention the issue number in your commit message(s) so we can link code changes to their source. I Look forward to seeing a PR!

**Comment by jbogaardt** [comment]
Resolved by #280
