### ISSUE TITLE
GridSearchCV with time-series cv functionality

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#29]
Need to create cross-validation functionality that holds out valuation dates similar to `sklearn.model_selection.TimeSeriesSplit`.

**Comment by jbogaardt** [comment]
Refer to https://www.actuarialsociety.org.za/convention/wp-content/uploads/2020/09/2020-ASSA-BalonaRichman-FIN.pdf paper for a well thought-out approach.

**Comment by aegerton** [comment]
Thanks, John. Good article. 


Anthony A H Egerton MA MBA ACII
李晋唐
Principal Officer 
HUNTINGTON UNDERWRITING LIMITED

G/F Brighton Place
U0215 Jalan Bahasa
PO Box 80431
87014 Labuan FT
Malaysia

T: +60 87 442 899
M: +60 17 2435 008 | +65 9128 1855
F: +60 87 451 899
aegerton@huntingtonunderwriting.com 
www.huntingtonunderwriting.com 

Licensed (#US201226) under the Labuan Financial Services and Securities Act 2010

CONFIDENTIALITY NOTE: 
 
The information contained in this email message may be legally privileged and contain confidential information and is intended only for the use of the individual or entity to whom it is addressed. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copy of this message is strictly prohibited. If you have received this email in error, please immediately delete this message.

**Comment by jbogaardt** [comment]
This has been published under the [tryangle](https://github.com/casact/tryangle) package and will not be reproduced here.
