### ISSUE TITLE
Issue on page /tutorials/triangle-tutorial.html

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#298]
Under "Triangle Methods not Available in Pandas", the 2011 having no data example has a code snippet repeated

**Comment by kennethshsu** [comment]
Hi @henrydingliu, can you elaborate what you are saying please? What section are you seeing the error?

**Comment by henrydingliu** [comment]
Right under "Let’s see what happens if we have no data for 2011."

**Comment by kennethshsu** [comment]
It is corrected in the [source code](https://github.com/casact/chainladder-python/blob/master/docs/tutorials/triangle-tutorial.ipynb) in the repo, but I think for some reason the readthedocs site is having trouble pulling in the latest files.

**Comment by kennethshsu** [comment]
Hello @MatthewCaseres, welcome!

It is corrected in the [source code](https://github.com/casact/chainladder-python/blob/master/docs/tutorials/triangle-tutorial.ipynb) in the repo, but I think for some reason the readthedocs site is having trouble pulling in the latest files. We will work on getting this resolved.

**Comment by kennethshsu** [comment]
I believe this is now resolved.
