### ISSUE TITLE
Issue on page /tutorials/tail-tutorial.html

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#304]
The code block under Chaining Multiple Transformers is slightly confusing. 

print("This doesn't pass") under the first try block should be a comment or be in the except block

print("This doesn't fail") under the second else block should be a comment or be in an else block.

**Comment by kennethshsu** [comment]
I think they make sense the way they are laid out right now. Why do you think otherwise? If the print statements aren't printed to the console, that means that the code blocks weren't executed.

```python
print("First attempt:")
try:
    cl.TailCurve().fit(cl.Development().fit(quarterly))
    print("This doesn't pass")
except:
    print("This fails because we did not transform the triangle")

print("\nSecond attempt:")
try:
    cl.TailCurve().fit(cl.Development().fit_transform(quarterly))
    print("This passes because we transformed the triangle")
except:
    print("This doesn't fail")
```
```
First attempt:
This fails because we did not transform the triangle

Second attempt:
This passes because we transformed the triangle
```

**Comment by henrydingliu** [comment]
The code executes fine. It's just the inherent paradox in having this doesn't pass in a try block and this doesn't fail in an except block.

**Comment by kennethshsu** [comment]
Ahh I see what you are saying now.

What if we do something like this?
```python
print("First attempt:")
try:
    cl.TailCurve().fit(cl.Development().fit(quarterly))
    print("This works.")
except:
    print("This fails.")

print("\nSecond attempt:")
try:
    cl.TailCurve().fit(cl.Development().fit_transform(quarterly))
    print("This works.")
except:
    print("This fails.")
```

I'll move the commentary to the body instead of the code. Do you think this is clearer?

**Comment by henrydingliu** [comment]
I think we can also add in the "This fails because we did not transform the triangle" and "This passes because we transformed the triangle" as comments

**Comment by kennethshsu** [comment]
Ahh ok, I think I get what you are saying now. Thank you. I'll get this in.
