### ISSUE TITLE
std_residuals_

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#331]
Prolly something dumb I'm doing. 

This code works.
```
raa = cl.load_sample('raa')
model = cl.Development().fit(raa)
model.std_residuals_
```

This code doesn't.
```
raa = cl.load_sample('raa')
model = cl.Development().fit_transform(raa)
model.std_residuals_
```

**Comment by jbogaardt** [comment]
I think this should work. I guess we haven't passed the `std_residuals_` property on to the transformed triangle.

**Comment by kennethshsu** [comment]
Done in [d3c8475](https://github.com/casact/chainladder-python/pull/352/commits/d3c8475b27bcbbc6d4afebb5b492fc968c5847e9).
