### ISSUE TITLE
Issue on page /development.html

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#333]
there is a note on this page that says

drop_high and drop_low are ignored in cases where the number of link ratios available for a given development period is less than 3.

the default value for preserve seems to be 1, not 3. not sure if this is a documentation error or the documentation actually reflects the original intent.

**Comment by kennethshsu** [comment]
That's right, `preserve` is a new variable, it used to be set to 3 and wasn't modifiable, but now `preserve` can be set by the user.

This documentation needs to be updated.

**Comment by kennethshsu** [comment]
This is now resolved, closing ticket.
