### ISSUE TITLE
Issue on page /tutorials/deterministic-tutorial.html

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#379]
cl.Pipeline seems to be fitting only and not transforming. Is that intentional?

```python
genins = cl.load_sample("genins")
genins_dev = cl.Development().fit_transform(genins)
genins_cl = cl.Chainladder().fit(genins_dev)
pipe = cl.Pipeline(steps=[
    ('dev', cl.Development()),
    ('model', cl.Chainladder())]
)
test = pipe.fit(X=genins)
print(type(genins_dev))
print(type(test.named_steps.dev))
```

**Comment by jbogaardt** [comment]
Yes, this is identical to sklearn:
```python
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
X, y = make_classification(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=0)

ss = StandardScaler().fit_transform(X_train, y_train)

pipe = Pipeline([('scaler', StandardScaler()), ('svc', SVC())])
pipe.fit(X_train, y_train)

print(type(ss))
print(type(pipe.named_steps.scaler))
```

**Comment by henrydingliu** [comment]
Ah, I think i'm getting confused by this [comment](https://github.com/casact/chainladder-python/blob/4766369bdd3d987619d63e4e425d3d4e480004ec/chainladder/workflow/gridsearch.py#L109). So how do I get the transformed intermediate steps?

**Comment by jbogaardt** [comment]
That verbiage is also a direct copy of sklearn's [Pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#:~:text=Sequentially%20apply%20a%20list%20of%20transforms%20and%20a%20final%20estimator.). The only way I know of getting a partial pipeline is to just reconstruct it with partial steps and fit that:
```python
cl.Pipeline(pipe.steps[:1]).fit_transform(genins)
```

**Comment by henrydingliu** [comment]
got it!
