### ISSUE TITLE
[BUG] Chainladder doesn't coerce valuation triangle correctly

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#399]
**Describe the bug**
See offending code below.

**To Reproduce**
Steps to reproduce the behavior. Code should be self-contained and runnable against publicly available data. For example:
```python
import chainladder as cl
raa = cl.load_sample('raa')
model = cl.Chainladder().fit(raa)
# works 
assert model.predict(raa.latest_diagonal.val_to_dev()).ultimate_ == model.ultimate_
# doesn't work
assert model.predict(raa.latest_diagonal).ultimate_ == model.ultimate_
```

**Comment by jbogaardt** [comment]
Resolved on master, will be in next release.

**Comment by tyler-corcoran** [comment]
Is this change reflected in the current release? I seem to be having an issue that is likely related.

**Comment by tyler-corcoran** [comment]
> Resolved on master, will be in next release.

Is this change reflected in the current release? I seem to be having an issue that is likely related.

**Comment by jbogaardt** [comment]
Not yet, we have not done a release since this went in. Release cadence has slowed somewhat as its my busy season.

If you want to test out the unreleased version and you have git, you should be able to install with:
```
pip install git+https://github.com/casact/chainladder-python/
```
This should at least let you see whether your specific issue is addressed with this bug-fix.
