### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by MatthewCaseres** [casact/chainladder-python#448]
https://jupyterbook.org/en/stable/advanced/html.html#enable-google-analytics

It might be fun to look at this kind of stuff

**Comment by jbogaardt** [comment]
We do have google analytics set up for the docs. Looks something like this over the last month. 


Happy to share individual access privately to those interested. Email me directly at jbogaardt@gmail.com.

**Comment by MatthewCaseres** [comment]
Very cool I just didn't find it when I went searching in the config so I opened the issue
