### ISSUE TITLE
New flaw in basic operation of the package

### ISSUE THREAD

**Issue by thearmchair47** [casact/chainladder-python#475]
**Describe the bug**
It seems some packages used in Chainladder have been updated and are leading to errors when using the package.

**To Reproduce**
Steps to reproduce the behavior. Code should be self-contained and runnable against publicly available data. For example:
```python
import chainladder as cl
triangle = cl.load_sample('raa')
```

**Expected behavior**
raa data to be imported, or any action that does not lead to an error.
Result when running:
ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

**Desktop (please complete the following information):**
 - Numpy Version [e.g. 1.24.3]
 - Pandas Version [e.g. 2.1.1]
 - Chainladder Version [e.g. 0.8.14]

**Comment by jbogaardt** [comment]
We've updated chainladder to be compliant with `pandas>=2.0`, but I think that was after `chainladder==0.8.14`. Can you try upgrading chainladder to 0.8.18 and see if that resolves your issue?
