### ISSUE TITLE
Help with BF

### ISSUE THREAD

**Issue by andreaeddyricci** [casact/chainladder-python#478]
I am using the BF method to predict ultimates.  I want to use an all year weighted average, as well as a five year weighted average.  Here is my code.  The ultimate and ldfs shouldn't be the same.

![image](https://github.com/casact/chainladder-python/assets/107001271/a15af85e-d5b2-4301-924e-71cadeae478e)

**Desktop (please complete the following information):**
 - Numpy Version 1.24.4
 - Pandas Version 2.0.3
 - Chainladder Version 0.8.17

**Comment by andreaeddyricci** [comment]
Hi John,

Thanks for the quick reply.  Here is a portion of my reported
triangle.  My 5-year
average LDF and the all year average LDF are different, which is what I
expected.  When I put these into the BornhuetterFerguson model though, the
LDFs become identical and thus the ibnr and ultimate are also identical,
which is not what I expected.  Let me know if you would like to see
anything else to better clarify.  Thanks again!

[image: image.png]

**Comment by jbogaardt** [comment]
Thanks for the additional explanation. I missed it in the code. 

You have both variable `triangle_bf_model5yr` and `triangle_bf_modelALLyr` pointing at the same BF instance `bf_model`. That is, they're sharing the same model and when you refit it, both get the same underlying model.  You can avoid this by creating separate instances and references the separate instances in your code:
```python
bf_model_5yr = cl.BornhuetterFerguson(apriori=0.7)
bf_model_ALLyr = cl.BornhuetterFerguson(apriori=0.7)
```
Key here is that `bf_model` is one instance. These models inherit from `sklearn` and the same behavior happens there:

```python
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1, 2, 3, 4]]).T
y1 = np.array([2, 4, 5, 8])
y2 = np.array([3, 6, 9, 12])

lm = LinearRegression()

model1 = lm.fit(X, y1)
model2 = lm.fit(X, y2)
# Similar behavior from scikit-learn models
print(model1.coef_ == model2.coef_)

lm2 = LinearRegression()
model1 = lm.fit(X, y1)
model2 = lm2.fit(X, y2)

print(model1.coef_ == model2.coef_)
```

**Comment by andreaeddyricci** [comment]
Wow, thank you so much.  I overlooked that.  I thought since I put
different triangles into the model, that I wouldn't need a different
instance.  I really appreciate your time and explanation.  Thanks again!
