### ISSUE TITLE
[BUG] Issue in method Common._validate_assumption (line 206) (chainladder/core/common.py)

### ISSUE THREAD

**Issue by FlawlessNa** [casact/chainladder-python#502]
Hi,
I was trying to use a `numpy.ndarray` object to pass in as the `n_periods` argument of `cl.Development(...)` constructor.
When calling the `.fit` method, this raises a `UnboundLocalError` from within `Common._validate_assumption`. (chainladder/core/common.py)

This is because of line 206, 
`if type(value) in (list, tuple, set, np.array):`

np.array is not a type but rather a function. To enable passing numpy arrays as argument for n_periods (and potentially other arguments?), the line 206 should be:
`if type(value) in (list, tuple, set, np.ndarray):`

Alternatively, perhaps the `_validate_assumption` method should provide more specific info, for example that n_periods should NOT be a `numpy.ndarray` object.

I am using version 0.8.18.
![image](https://github.com/casact/chainladder-python/assets/106719178/9441fc60-f444-4522-814a-f8891665e51e)

Thank you!

**Comment by jbogaardt** [comment]
sorry for not writing back - thanks for the report and fix recommendation. I've included those in master branch for the next release.
