### ISSUE TITLE
[MAINT] Pandas deprecation notices

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#510]
**Is your feature request related to a problem? Please describe.**

There are several pandas deprecation notices with pandas 2.2 and later.  These should be handled and silenced. The most common is our usage of the `infer_datetime_format`.

```python
chainladder/core/base.py:250: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
```

**Is your feature request at odds with the scope of the package?**
No

**Describe the solution you'd like**
No pesky deprecation notices regardless of which version of pandas is installed.

**Comment by kennethshsu** [comment]
@jbogaardt did you resolve this?

**Comment by jbogaardt** [comment]
I have not, but it probably makes the most sense to explicitly set date formats of datasets within the package to silence it for training purposes, but otherwise persist the deprecation.

**Comment by kennethshsu** [comment]
Hmm, can you elaborate more on what you mean? 

There's a PR on what I think fixes the issue, it's just using the version package to check for versions.
