### ISSUE TITLE
dropna + grain

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#63]
`dropna` will create triangles with odd shapes and these will not always work with `grain`.  Need to make `grain` function work better with these odd shapes.

**Comment by peterdavidsonONE** [comment]
I noticed that cl is dropping Na's incorrectly for development factors.
Consider a triangle with no claims in first development period of a accident month. Passing the data fills it as na (but it should be zero). The development factors ignore the 1-2 contribution from this accident month, which understates the development factors. I think a fillna(0) is needed somewhere when the triangle is built to put zeros in the upper left of the triangle.

**Comment by jbogaardt** [comment]
@peterdavidsonONE , can you help me understand this one a bit better?  The part I don't understand is that if an entire development period is 0, then whether it is `nan` or 0 it is undefinable from the data.  I'm supplying some starter code to replicate the issue (I think) - can you elaborate on the code below to highlight the issue?
```python
import chainladder as cl
tri = cl.load_dataset('raa')
tri.values[0,0,:, 0] = 0 # Setting age 12 amounts to zero
tri.dropna() # drops age 12 entirely from the triangle
```


Origin | 24 | 36 | 48 | 60 | 72 | 84 | 96 | 108 | 120
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1981|8,269 | 10,907 | 11,805 | 13,539 | 16,181 | 18,009 | 18,608 | 18,662 | 18,834
1982|4,285 | 5,396 | 10,666 | 13,782 | 15,599 | 15,496 | 16,169 | 16,704 |  
1983|8,992 | 13,873 | 16,141 | 18,735 | 22,214 | 22,863 | 23,466 |   |  
1984|11,555 | 15,766 | 21,266 | 23,425 | 26,083 | 27,067 |   |   |  
1985|9,565 | 15,836 | 22,169 | 25,955 | 26,180 |   |   |   |  
1986|6,445 | 11,702 | 12,935 | 15,852 |   |   |   |   |  
1987|4,020 | 10,946 | 12,314 |   |   |   |   |   |  
1988|6,947 | 13,112 |   |   |   |   |   |   |  
1989|5,395 |   |   |   |   |   |   |   |

**Comment by peterdavidsonONE** [comment]
It is to do with no values in the data. If the entry is zero or missing in the data, the Triangle method puts a NaN. 
In this example below, origin 1983, development 1-2 is excluded from the ldf whereas it should have values 0, 8992 considered.

`tri = cl.load_dataset('raa')
df = tri.unstack().to_frame()
df = df.reset_index()
df['dev']= df['level_0']
df['origin']= df['level_1']
df['claim']= df[0]
df.drop(columns=['level_0', 'level_1'], inplace=True)
df.drop(columns=[0], inplace=True)
df.origin = df.origin.astype(int) + 1970
df.dev = df.dev/12 -1
df.dev= df.dev.astype(int)
df.dev = df.dev + df.origin
df.loc[2, 'claim'] = 0
tri = cl.Triangle(df, origin = 'origin', development = 'dev', columns=  ['claim'])`

**Comment by jbogaardt** [comment]
I understand the issue now.  Thanks.  This is one that I think has larger implications.  The `Development` estimator doesn’t actually fit patterns as directly as you show.  Instead it relies on a weighted regression framework proposed by [Thomas Mack](https://www.actuaries.org.uk/system/files/documents/pdf/crm2-D6.pdf). 

Essentially, the patterns are fit using a weighted regression through the origin.  For ‘volume’ weighted, the weights are the 1/(denominator of link ratio) which in this case is creates division by zero error and is why the observation is excluded from the estimate.  ‘simple’ and ‘regression’ fail too because the link ratio itself throws a division by zero error.  We use this framework for compatibility with the `MackChainladder` estimator. 

It’s not clear to me yet how to support a zero in the denominator of the link ratio while also making the `Development` estimator compatible with the Mack model.  I think this is more an issue with the actuarial theory underlying the Mack model and the regression framework.  Perhaps a follow up paper to Mack has been written that addresses the issue, but I am not aware of it.  If pointed in the right direction, I’d be happy to read and/or take suggestions on how to address the problem.

**Comment by jbogaardt** [comment]
@peterdavidsonONE , here is a possible solution/hack for your issue. 
```python
import chainladder as cl
raa = cl.load_dataset('raa')
raa.values[0,0,2,0] = 0 # 0 in demonimator of link ratio
raa = raa + 0.0001      # Add some arbitrary small amount

volume = cl.Development().fit_transform(raa)
volume.ldf_[volume.ldf_.development=='12-24']

raa = raa - 0.0001 # Put triangle back to normal
```
Origin | 12-24
-- | --
(All)|3.5546

Notice the `simple` average produces ridiculous results:
```python
simple = cl.Development(average='simple').fit_transform(raa)
simple.ldf_[simple.ldf_.development=='12-24']
```
Origin|12-24
-- | --
(All)|9,991,119

As well, notice the insane `mack_std_err_` of the `MackChainladder`  for the current accident year even when using `volume` average method:
```python
cl.MackChainladder().fit(volume).summary_
```
Origin | Latest | IBNR | Ultimate | Mack Std Err
-- | -- | -- | -- | --
1981|18,834 | 0 | 18,834 | 0
1982|16,704 | 154 | 16,858 | 22
1983|23,466 | 617 | 24,083 | 562
1984|27,067 | 1,636 | 28,703 | 680
1985|26,180 | 2,747 | 28,927 | 1,436
1986|15,852 | 3,649 | 19,501 | 1,989
1987|12,314 | 5,435 | 17,749 | 2,199
1988|13,112 | 10,907 | 24,019 | 5,351
1989|5,395 | 10,650 | 16,045 | 6,330
1990|2,063 | 19,746 | 21,809 | 45,285,793

I suppose we could have a `fillna` parameter in the `Development` object that defaults to `None`.  You could do `cl.Development(fillna=0.0001)` or some other arbitrary small amount to get what you want out of a deterministic volume-weighted average.  It would behave similar to the "hack" above. It would also be on the user to make use of the feature, as it wouldn't (by default) interfere with the functioning of the broader package.  That's the closest to a workable solution I can come up with.

Thoughts on the approach?
