### ISSUE TITLE
support pandas>=1.0.0

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#64]
Biggest issue seems to be comparisons between `PeriodIndex` and `Timestamp` are no longer valid.

**Comment by albertkuller1983** [comment]
Hi John, has this issue been resolved? Albert

**Comment by jbogaardt** [comment]
As of now, its still unresolved.  Would need to 
1. create environment for upgraded pandas
2. Run unit tests
3. Where failing see if fails can be fixed with extra code

I haven't prioritized this yet since I'm not using `pandas>=1.0.0`.

**Comment by jbogaardt** [comment]
@albertkuller1983 , I knocked this one out. Feel free to
 `pip install git+https://github.com/casact/chainladder-python/` or wait until `v0.5.5` is released.

I want to play around with it a bit more before releasing in case I introduced latent bugs.  I had to fundamentally change the object type of the `valutation` property of the triangle which gets used extensively throughout the project.

**Comment by albertkuller1983** [comment]
Hi John,

Thanks for the update, I will give it a try.

Regards,
Albert
