### ISSUE TITLE
Tutorial example fit function not working 

### ISSUE THREAD

**Issue by nassmim10** [casact/chainladder-python#65]
Hi,

I am trying to learn how to use your module but I am having issues with your example. I could not run some of the Development methods and thus I decided to try only with your included dataset. However it still does not work.

I have copied pasted the following code:

genins = cl.load_dataset('genins')

genins_dev = cl.Pipeline(
    [('dev', cl.Development()),
     ('tail', cl.TailCurve())]).fit_transform(genins)

This works.

Then when I run genins_model = cl.Chainladder().fit(genins_dev), I get the error message below:
'NaTType' object has no attribute 'to_timestamp'

Would you know where this comes from?

Best,
Nassim

**Comment by jbogaardt** [comment]
I suspect this might be related to a bug in a previous version of `chainladder`.  Which version are you on?  
```python
import chainladder as cl
cl.__version__
```
I am on version 0.5.2 (latest available) and the tutorial works as intended.  Try installing latest:
`pip install chainladder==0.5.2`
If you still have issues, let me know.

**Comment by nassmim10** [comment]
Hi @jbogaardt  it works fine with the latest version. Maybe worth changing this statement at the beginning of the tutorial: "All exercises rely on chainladder v0.4.5 and later. :)

Thanks very much for your responsiveness!!

Best
