### ISSUE TITLE
arithmetic fail

### ISSUE THREAD

**Issue by jbogaardt** [casact/chainladder-python#68]
offending code throws error:
```python
import chainladder as cl
raa = cl.load_dataset('raa')
raa.latest_diagonal / raa
```

**Comment by gig67** [comment]
I am not clear what is the issue. 
latest_diagonal is a 10x1 array, raa is 10x10 so there is a dimension mismatch that cannot be obviously solved in both directions
```raa / raa.latest_diagonal``` works and makes sense (the relative values of the triangle based on the latest valuation)
What would be expected from ```raa.latest_diagonal / raa``` ?

**Comment by jbogaardt** [comment]
I would expect a `Triangle` to honor the broadcasting rules of numpy.  If numpy allows this arithmetic, then chainladder should as well.  
```python
raa.latest_diagonal.values / raa.values # works for numpy arrays
raa.latest_diagonal / raa # doesn't works on Triangles, but why shouldn't it?
```
This particular example is contrived and not very useful, but it highlights that the arithmetic of the package is not as flexible as it could be.

**Comment by gig67** [comment]
The case you mention fails in _nan_triangle on line 169 (a reshape operation) withe error ```cannot reshape array of size 10 into shape (10,10)```. 

My understanding of what happens is that
1) dividing latest_diagonal (size 10,1) by raa (size 10,10) invokes __truediv
2) as a first step, __truediv creates obj with shape (1,1,10,1)
3) __truediv then calculates obj.values as the numpy division of the two arrays, resulting in shape (1,1,10,10). This may happen also with other operators when the two operands have different shapes and broadcasting occurs
4) So here we have a mismatch between the shapes of obj and of obj.values. Trying to display obj at this stage causes an error: Shape of passed values is (10, 10), indices imply (10, 1).
5) in the next step _arithmetic_cleanup is applied to obj, and so obj.nan_triangle() is invoked
6) here I get lost because obj.valuation is being used instead of obj.values but I think step 4 needs to be addressed before and maybe that fixes it.

**Comment by jbogaardt** [comment]
Ah, yes.  You're correct. The purpose of `_nan_triangle()` is to easily censor the lower half of the triangle.  Array operation apply to the entire `values` array and sometimes this creates irrelevant elements in the lower half of the triangle that need to be removed. This is easy enough if we have an array `_nan_triangle()` that has NAN values beyond the valuation date and 1s everywhere else.  You'll see that we multiply by `self._nan_triangle()` liberally in the package to maintain calculations on just the upper half.

As you've noted, that while we seem to be broadcasting the `values` correctly, something is amiss on the other properties of the `Triangle`.  The `origin`, `development`, and `valuation` vectors don't attempt to broadcast and just take the left-hand side of the arithmetic operation.  In this case, the valuation obviously doesn't align well.

_Can there be a general rule to indicate what should be the origin and development years of the resulting triangle of a division or multiplication?_  Throwing `valution` in to the mix, I hope there is a general rule that gets us 90% of the way there.  Maybe picking these vectors from the "larger" shaped object? 

_Should we add / subtract triangle values when their origins or development years are different?_  I want to fiercely advocate that we should allow this and my advocation goes beyond broadcasting.  This would support common operations like adding another  diagonal to an existing triangle.
Something like:
```python
last_year = raa[raa.valuation<raa.valuation_date]
new_diagonal = raa.latest_diagonal
this_year = last_year + new_diagonal
```
Incidently, this fails too :(

**Comment by jbogaardt** [comment]
Also throwing out that using pandas for any largish triangle poses a real problem. the 'clrd' triangle is a good example since it is 1000+ triangles in one.  Iterating over these in pandas would severly cripple the speed of the operations.  I currently use pandas only for the `origin`, `development`, and `valuation` vectors, but never for `values` because its just too slow.

**Comment by gig67** [comment]
I am surprised of your bad experience with pandas, which I usually find quite fast. It's important to avoid for-loops though. cudf is a GPU-accelerated version for pandas, where needed. I do Monte Carlo simulations in pandas with vector operations on millions rows in seconds. 
Still, I am not suggesting to switch to pandas at such an advanced stage, but it should be seen as a reference for its very consistent and "pythonic" way of dealing with indexing which can be frustrating but forces users to think about what they want: "In the face of ambiguity, refuse the temptation to guess."

I think the operations you suggest are all useful, provided that they remain consistent with indexing.
One way to do so could be to use the pandas operations on the to_frame() of the operands, such as self.to_frame().add(obj.to_frame()) and then convert the result into a triangle. 
Where the result looks odd, the user can think better about the desired outcome.   

The current to_frame() only works on the basic 2D triangle, to convert the full 4D there are some ideas here if it is of interest: https://stackoverflow.com/questions/45422898/how-can-i-efficiently-convert-a-4d-numpy-array-into-a-pandas-dataframe-with-indi

**Comment by jbogaardt** [comment]
> Still, I am not suggesting to switch to pandas at such an advanced stage, but it should be seen as a reference for its very consistent and "pythonic" way of dealing with indexing which can be frustrating but forces users to think about what they want: "In the face of ambiguity, refuse the temptation to guess."

I agree.  The problem with chainladder arithmetic is it is not well thought out.  It was built for the basic case of same shaped triangles and then has evolved based on the needs I had on any given day.  It deserves a comprehensive review of legal vs illegal operations and anchoring to the rules of a prominent package where these operations are battle tested sounds like a good idea.

**Comment by gig67** [comment]
Below is a test for a 4D array to pandas conversion. On my laptop, on a 2.7m elements array, It takes a few secs to build the index, which may be unnecessary in Triangle, and another couple of seconds to build the dataframe. BTW you are right that numpy is much faster than pandas, but for normal size triangle there would hopefully be no practical difference.  
```
test=np.array(np.random.randint(0,10,(20,150,30,30)))
cols = ['a','b','c','d'] # or try ['comp','LOB','orig','dev']
idx = [list(map(''.join,itertools.product(cols[i],map(str,range(test.shape[i]))))) for i in range(len(cols))]
idx=list(itertools.product(*idx))
# idx is now [('a1','a2','a3',...),('b1','b2',...),...]
idx=pd.MultiIndex.from_tuples(idx,names=cols)
print('df conversion starts now')
df = pd.DataFrame(data=test.ravel(), index=idx, columns=['value'])
df.unstack()
```
elementwise operations such as  ```df.unstack()*df.unstack()``` take a comparable time, 
so we could put ```try: <pandas operation> except: <exception message>``` in dumbers.py

Alternatively, one could keep the numpy approach, adding a comparison of the origin and development indices of the two triangles and if they do not match produce at least a warning - this would be very fast.

**Comment by jbogaardt** [comment]
Thanks, as you noted earlier, borrow rules from pandas makes sense, but adopting the pandas DataFrame directly to support arithmetic is a substantial refactor and needs careful consideration.  We probably should treat code as secondary to defining the set of legal operations supported by the package.  With those in hand, deciding between pandas or numpy should be an easier decision.  

I do very much like the warnings idea and more generally exception handling.  We don't do enough of that in general and most folks don't have a clue why their code is failing.  The exception handling of the package is outright awful and probably warrants its own github issue.

**Comment by jbogaardt** [comment]
A first pass at arithmetic rules.

* [ ] We will support arithmetic between triangles and other triangles, ndarrays, and numeric scalars.
* [ ] We will not support arithmetic between triangles and lists, dictionaries, DataFrames, and non-numeric types
* [ ] We may possibly (but not likely any time soon) allow for arithmetic between triangles and Xarray datasets.

#### Triangle to Triangle index/column arithmetic
These conform exactly to Pandas DataFrame arithmetic
* [ ]  Adding single index/columns without assignment should return a triangle with anonymous column name
* [ ] If index/column doesn't align, union them and fill with NaN when more than one index/column are in the arithmetic expression
#### Handling of Accessors
* [ ] Union should be governed by `origin` and `valuation` and not `development` since `development` data type can vary and is not reliable for triangle cell coordinates.  This should support adding new diagonals to a triangle.
* [ ] If origin/valuation don't align, union the two and fill with 0, similar to index/column unions. This should solve the bug that conceived this ticket.
* [ ] Will not allow arithmetic of triangles of different grains - need clear exception handling.
* [ ] Warn when adding a cumulative and incremental triangle
* [ ] Will not support arithmetic of valuation triangles with development triangles - need  clear exception handling

#### Triangle and number arithmetic
* [ ] If adding int or float to triangle, preserve all axes as they are.
* [ ] Can we support `log` and `exp`, perhaps only through `cl.log` and `cl.exp` functions?
#### Triangle and ndarray arithmetic
* [ ] Will not support broadcasting triangles to array shape, but will support broadcasting array shape to triangle.  This is necessary to keep the triangle axis labels unambiguous.
* [ ] Array axes are assumed to be the Triangle's axes.
* [ ] array + Triangle -> `numpy` takes precedence if on lefthand side and will fail unless we monkey patch numpy. Can/should we?
