### ISSUE TITLE
Problems converting a triangle to a higher grain using the grain method

### ISSUE THREAD

**Issue by inesfcmarques** [casact/chainladder-python#69]
I created a dataframe with OriginDates and Development Dates, from 01-01-2017 to 31-12-2019, and a payment value of 1 for each Origin Month-Development Month.

Then, the incremental triangle with Origin in Months and Development in Months will have a value of 1 in each cell. I created this triangle with the chainladder package and it is ok.

However, when I try to transform the incremental triangle to Origin in Years and Development in Years, using the grain method, the result is:
______ 11___ 23___35
2017  66.0  144.0  144.0
2018  66.0  144.0    NaN
2019  66.0    NaN    NaN

But to be correct, it should be:
______ 12___ 24___36
2017  78.0  144.0  144.0
2018  78.0  144.0    NaN
2019  78.0    NaN    NaN

I also tried to transform first the triangle into cumulative, but it still doesn't show the expected triangle.

`Code:`
datesm = pd.date_range('2017-01-01', '2019-12-31', freq='M')

origin_months = datesm.repeat(repeats=list(range(36,0,-1)))

dev_months = list()
for i in range(len(datesm)):
    dev_months.extend(datesm[i:len(datesm)])

incremental_payments = [1]*len(origin_months)

dict = {'AccidentMonths':origin_months, 'DevelopmentMonths':dev_months, 'Payments':incremental_payments}
testdf = pd.DataFrame(dict)

xMM = cl.Triangle(data=testdf, origin='AccidentMonths', development='DevelopmentMonths', columns='Payments')

xYY = xMM.grain('OYDY')

![xMM](https://user-images.githubusercontent.com/62303809/76890822-f47a1c00-687f-11ea-9420-4ee2011bf8ed.jpg)
![xYY](https://user-images.githubusercontent.com/62303809/76890831-f8a63980-687f-11ea-90fa-91a68917f1cd.jpg)

Thank you!

**Comment by jbogaardt** [comment]
Seems to be an issue when dealing with datetime coolumns on initialization.  Changing your dates as follows makes the triangle properly construct:
```python
testdf['AM'] = testdf['AccidentMonths'].dt.strftime('%Y-%m')
testdf['DM'] = testdf['DevelopmentMonths'].dt.strftime('%Y-%m')
xMM = cl.Triangle(data=testdf, origin='AM', development='DM', columns='Payments')
```
Nevertheless, this should work, so we will resolve it. Thanks for reporting it!

**Comment by jbogaardt** [comment]
@inesfcmarques,

This has been fixed and will be available in the next release.  In the meantime, feel free to use the 'reformatting' approach above or install the master branch of the repo.
`pip install git+https://github.com/casact/chainladder-python/`

Thanks again for reporting this.
