### ISSUE TITLE
Data structure documentation

### ISSUE THREAD

**Issue by gig67** [casact/chainladder-python#75]
I appreciate very much this project but I find it difficult to get it started on my data.
Loading a dataframe directly into a triangle is not explained. Loading from a file is also not explained, unless it is one of the sample files. 
I went through the code of the "load_dataset" function and it seems that the data structure must contain both origin and development year as integers, while timestamp is not OK and higher granularity (eg "YYYY-MM") is also not OK. 
So the concept of "grain" in Triangles must mean that you can switch to a finer grain but the analysis is only done at year level. That is a bit confusing.
It also seems that other dimensions (eg line of business, company) can be added looking at how load_dataset works, but the "how" is not documented.
It's unclear if the developmentLag used in the 'clrd' example is useful to a Triangle or is discarded
It would be great if the documentation could be clearer.
As I have monthly data I am still working on resampling it and hopefully the above clarifications will suffice.

**Comment by jbogaardt** [comment]
Hi @gig67 . `load_dataset` is a convenience function for sample data only.  It wouldn't be used in any real world context.  For real world context, you'd load a pandas dataframe and it is mentioned in [Initializing a triangle with your own data](https://chainladder-python.readthedocs.io/en/latest/tutorials/triangle-tutorial.html#Initializing-a-triangle-with-your-own-data).  That part of the tutorial goes through loading a dataframe with and without other dimensions.  The basic format would look something like this.
```python
my_triangle = cl.Triangle(df, origin="Accident Year", development="Valuation Year", index="Line of Business")
```
As far as how you create the pandas dataframe, (from file, from database, etc), that is up to you and is out of scope of this package.

As you note on `clrd`, the `developmentLag` column is discarded.  The Triangle currently supports date-like vectors for `origin` and `development` and an "Lag" does not fit this.

**Comment by gig67** [comment]
Thanks, I got it to work. Documentation is good but skinny for a package of this level of complexity, and I appreciate that it is already a big effort to document to this level. Is there any additional publication which provides more details and examples?

**Comment by jbogaardt** [comment]
Thank you for the feedback as well as the recognition for the work involved in building and maintaining a package like this.  As both the  developer and documentor, I definitely miss what is and is not clear to others.  Feedback like this helps.  For example, I probably should rename `load_dataset` to something like `load_sample_data` .  Reopening the issue to flag this change. 

Unfortunately there is is no additional documentation.  That said, I try to keep as close `pandas` and `sklearn` as possible, both of which have a tremendous amount of documentation.

Community involvement would help immensely in making the package and docs better. Until that happens, fielding questions like this feels like the only way to give some balance to my free time.  So don't hesitate to ask questions.  I'd be happy to answer and I'd benefit from getting a glimpse into how people use the package, their struggle points, potential new features, etc.
